### ISSUE TITLE
stable method for cov-matrix inverse

### ISSUE THREAD

**Issue by Wangxuefeng92** [rpng/open_vins#101]
hello, Is there have a more robust method for the INVERSE for "S = H * P_small * H.transpose() + R"? because the numerical problem had happend when I use LLT.

**Comment by goldbattle** [comment]
If there is a numerical issue with LLT then that likely means that there is a further underlying issue in your measurement noise or your state estimation has gone wrong. Measurement covariance S should be **Positive definite** in nature, thus LLT is well suited for this. If you do want to look at other inverses you can checkout this Eigen page:
https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html
![image](https://user-images.githubusercontent.com/2222562/93694276-bc29f380-fad7-11ea-805f-38cb3512427e.png)
