### ISSUE TITLE
A typo in TrackBase.h

### ISSUE THREAD

**Issue by zhuqingzhang** [rpng/open_vins#105]
In the function of set_calibration of Class TrackBase, there is a typo I guess. In the 107th line, 

`if(mtx_feeds.empty() || camera_k_OPENCV.empty() || camera_k_OPENCV.empty() || this->camera_fisheye.empty())`

there are two "camera_k_OPENCV.empty()", and I assume one of these should be "camera_d_OPENCV.empty()", although it should not effect the performance of code.

**Comment by goldbattle** [comment]
Thanks for the correction!

**Comment by goldbattle** [comment]
Addressed in #117.
