### ISSUE TITLE
Slow estimation when feeding measurements in sub-real time

### ISSUE THREAD

**Issue by aaaaronlin** [rpng/open_vins#110]
I am using OpenVins on simulated images and IMU readings in sub-real time without ROS by calling functions in VioManager directly. Generation of images and IMU takes ~0.3 sec on average but estimation has approached ~1 second.

Is this method of inputting data unsuitable at the moment, or is it an implementation error on my end?

[34m[TIME]: 0.0105 seconds for tracking
[0m[34m[TIME]: 0.0207 seconds for propagation
[0m[34m[TIME]: 0.9564 seconds for MSCKF update (40 features)
[0m[34m[TIME]: 0.1145 seconds for SLAM update (29 feats)
[0m[34m[TIME]: 0.0000 seconds for SLAM delayed init (0 feats)
[0m[34m[TIME]: 0.0039 seconds for marginalization (11 clones in state)
[0m[34m[TIME]: 1.1059 seconds for total
[0mq_GtoI = 0.001,0.001,0.003,1.000 | p_IinG = -0.006,0.009,1.631 | dist = 1.34 (meters)

I have also created launch configurations using the same simulated images and IMU readings, and performance using ros_serial is much faster.

[TIME]: 0.0081 seconds for tracking
[TIME]: 0.0002 seconds for propagation
[TIME]: 0.0098 seconds for MSCKF update (25 features)
[TIME]: 0.0029 seconds for SLAM update (22 feats)
[TIME]: 0.0000 seconds for SLAM delayed init (0 feats)
[TIME]: 0.0008 seconds for marginalization (11 clones in state)
[TIME]: 0.0218 seconds for total

**Comment by goldbattle** [comment]
Are you generating the measurements using the included simulator? Typically 40 features in an MSCKF update is quite a lot, so not sure how many features you are tracking, but it could be that expensive. Overall though it seems that you have much higher execution times. Are you compiling in release mode or debug mode?
