### ISSUE TITLE
Error State Derivation

### ISSUE THREAD

**Issue by SubMishMar** [rpng/open_vins#112]
Hi, Thanks for such nice documentation of important derivations related to IMUs. I just have some questions about the rotation error state derivation. 
Specifically the following: 
![Screenshot from 2020-10-30 13-50-52](https://user-images.githubusercontent.com/28704031/97745643-2eb6c780-1ab7-11eb-8d36-d1485dad64a2.png)
Can you refer me to some reading or sources on this, because I am unable to reach at the same results as you have.

**Comment by goldbattle** [comment]
Sola's work might be helpful (section 4.3 and 4.4): 
http://www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf

Note that they should be using a different rotation convention, what was is important is that throughout the codebase we use the same error state. In this case we model the error as being on the left side of a global to local rotation with a negative error. 
![image](https://user-images.githubusercontent.com/2222562/97747731-ccfc5a80-1ac2-11eb-817d-e7eb2e1f7f7c.png)
Additionally, we use quaternions in the codebase / state vector, but here it is easier to perform the derivation in SO(3) notation which is equivalent to its quaternion counterpart.

**Comment by SubMishMar** [comment]
Okay, I will check it out and get back to you. Thanks. 

Also, how did you arrive at:
![Screenshot from 2020-10-30 13-55-19](https://user-images.githubusercontent.com/28704031/97747025-4bec9580-1ab9-11eb-9093-b7cf145258e3.png)

As far as I understand:
![CodeCogsEqn](https://user-images.githubusercontent.com/28704031/97748747-f36ac780-1abb-11eb-85fc-d7d854e9bc43.png)

Why there is a -ve sign?

**Comment by WoosikLee2510** [comment]
No, the other way.
w is the god-knows truth,
w with hat is the hat is the measurement (or estimated value).
You are subtracting true-measurement, thus your first eq has the minus sign

**Comment by SubMishMar** [comment]
Oh! Ok. 

I am wondering why I thought the other way. I always thought the hat operator is not the measurement, probably because of the following:
![Screenshot from 2020-10-30 14-40-47](https://user-images.githubusercontent.com/28704031/97749982-f666b780-1abd-11eb-97d6-2da253562512.png)
![Screenshot from 2020-10-30 14-40-59](https://user-images.githubusercontent.com/28704031/97749986-f8307b00-1abd-11eb-90f4-74e63e6707a7.png)

But here hat refers to expectation (expected value) of the truth.

**Comment by WoosikLee2510** [comment]
O- wait, I made a mistake.

w_hat is what you get from w_measurement and estimated bias b_hat, thus it is the estimated w so we use w_hat.

**Comment by WoosikLee2510** [comment]
Let me clean this mess.

From https://docs.openvins.com/propagation.html,

w_m = w_true + b_true + n.
<-> w_true = w_m - b_true - n
you get the estimated w_hat by using estimated bias b_hat:

w_hat = w_m - b_est

thus the error of the estimated w, w_tilda is:

w_tilde = w_true - w_hat = w_m - b_true - n - w_m + b_est
 = - b_true + b_est  - n (we define error always true - est, so b_tilde = b_true - b_est)
 = - b_tilde - n

**Comment by SubMishMar** [comment]
![2020_10_30 3_03 PM Office Lens](https://user-images.githubusercontent.com/28704031/97752255-a984e000-1ac1-11eb-8d13-4fec657850c3.jpg)

Yes. Even I derived the same. Basically, the terms with \tilde are errors with \hat are estimations of the god knows unknown truth and the terms without any symbols on them are the god knows unknown truths.

**Comment by WoosikLee2510** [comment]
correct!

**Comment by SubMishMar** [comment]
Correct me if I am wrong. In the documentation provided here: https://docs.openvins.com/propagation.html

We have (?)

![CodeCogsEqn](https://user-images.githubusercontent.com/28704031/97757784-78a9a880-1acb-11eb-8330-77ce129ac15e.png)

Is there a special motivation/interpretation behind setting,
![CodeCogsEqn](https://user-images.githubusercontent.com/28704031/97757920-cb836000-1acb-11eb-8348-9c0e517f7a48.png)

**Comment by SubMishMar** [comment]
I think I understood the notation. This is how:
![2020_10_30 5_56 PM Office Lens](https://user-images.githubusercontent.com/28704031/97763402-80704980-1ad9-11eb-80c9-f9d37f1229d6.jpg)
Interpreted it in 2D for simplicity.

**Comment by SubMishMar** [comment]
Although I got a hang of the rotation equations in the EKF, I now have some problems with the position and the velocity parts. Especially with the following:
![Screenshot from 2020-10-30 22-55-55](https://user-images.githubusercontent.com/28704031/97770650-26847980-1b03-11eb-9707-211de4f1cb3b.png)

I am unable to derive the same. The result I obtain is below:
![2020_10_30 10_51 PM Office Lens](https://user-images.githubusercontent.com/28704031/97770758-15883800-1b04-11eb-88af-3d97a477c985.jpg)

**Comment by goldbattle** [comment]
In general it is not wise to try to subtract two rotation matrices. You might want to try leaving it as (R_true - R_hat)*g here. I believe in our documentation we have already pulled out the gravity term since it is independent to orientation change since it is in the global frame. If you want to go this route, you can try to substitute in and see if you can get the cancellations to remove the rotation in front of gravity.

**Comment by SubMishMar** [comment]
I am not really subtracting the way one subtracts A-B. I have rather used the Taylor series expansion of R_true around R_hat.  Let my try what you have suggested in my derivations... I may want to estimate g as well as done in the tech report by Joan Sola which you referred me to earlier..

**Comment by SubMishMar** [comment]
Is there any special motivation behind doing a left hand approximation of rotational error?

**Comment by goldbattle** [comment]
If you want to estimate g, you would directly perturb and get a Jacobian of -I_3*dt for velocity for example:
![image](https://user-images.githubusercontent.com/2222562/97908911-55723980-1d15-11eb-96e6-8631e3c29ff7.png)
Be warned that estimating gravity makes the system more unobservable (removes the roll and pitch observability).

Any form can be picked (for example right hand error is good for observability reasons as in the MSCKF 2.0 paper, which we address through FEJ), but this was picked purely based on convention with existing MSCKF literature.

**Comment by SubMishMar** [comment]
I got what you meant by pulling out the gravity terms and that makes the derivation easy..
![errStateAccel](https://user-images.githubusercontent.com/28704031/98189539-c9aa0a00-1eda-11eb-8207-8704dc32ec8c.jpg)

One need not define \delta a and can directly derive the error state mean propagation for velocity and reach at the same result that you have..


![errstate](https://user-images.githubusercontent.com/28704031/98189712-25749300-1edb-11eb-8bb2-959beaa3bc7b.jpg)

**Comment by SubMishMar** [comment]
I am trying to dig deeper into the code. Especially the parts concerning State Propagation. You mention in the [documentation](https://docs.openvins.com/classov__msckf_1_1State.html) "This state has all the current estimates for the filter. This system is modeled after the MSCKF filter, thus we have a sliding window of clones." I am little confused by what is meant by clones here? I think you are talking about a window of state values between time t_{k-n} to time t_{k}, where n is the size of the sliding window. I may be wrong, so I want to double check.

**Comment by goldbattle** [comment]
Cloning is the procedure of "cloning" the current pose such that after cloning there are two copies of the pose.
One will advance forward in time, while the other will remain at the historical time.

These related works should help (which should be cited from the original MSCKF paper if I remember correctly):
https://www-users.cs.umn.edu/~stergios/papers/sc-kf_icra02.pdf
https://www-users.cs.umn.edu/~stergios/papers/TRO-SC-KF.pdf

**Comment by goldbattle** [comment]
Feel free to re-open when you have any further issues.

**Comment by SubMishMar** [comment]
This might be a naive question but I do not understand why do we need a jerk to initialize the VIO? Especially for stereo, where the scale is already known? 
Even for mono, won't two (or three) different frames with smooth motion between them suffice to initialize the VIO?

**Comment by goldbattle** [comment]
The jerk is just to detect when the IMU starts moving and classify which segment is stationary if this is what you are referring to. Right now we don't have SFM initialization, so you need this stationary detection phase to perform our [stationary initialization procedure](https://docs.openvins.com/classov__core_1_1InertialInitializer.html). I believe I have answer this before, so I recommend searching the issues for "initialization (e.g. #58 and others have some details that might help you).

Open another issue if you have any further questions about initialization after looking through the past ones.

**Comment by FengQiaojun** [comment]
I want to follow up on the question regarding the transition function of rotation error.
In this part
<img width="711" alt="image" src="https://user-images.githubusercontent.com/32551664/202767596-f36b6984-ac0d-4e21-a58e-d5786978715d.png">
Do we use these tricks?

${}^{I_{k+1}}_{I_k}\mathbf{R} = \exp(-\boldsymbol{\omega}\Delta t)$   ->   Write the rotation matrix as the exp map of augular velocity
$\exp\left(\theta + \delta\theta \right) \approx \exp(\theta) \exp(\mathbf{J}_r(\theta)\delta\theta)$ for small $\delta\theta$
$\exp(-\delta\theta) \approx \mathbf{I} - \lfloor \delta\theta \rfloor$ for small $\delta\theta$

And should we convert from above to this
<img width="435" alt="image" src="https://user-images.githubusercontent.com/32551664/202767651-72a79844-407b-48c4-b8fe-04cc4662b42b.png">
Originally it was an equation between two 3x3 matrices and the final result is an equation between two 3-d vectors. How is this achieved? I guess I miss some tricks of converting skew symmetric matrix/cross product.

Any hints or guidelines are appreciated!

**Comment by FengQiaojun** [comment]
OK I got some idea on how the approximation between two matrices is converted to the approximation between two vectors. 
The main idea is to convert both sides to skew-symmetric matrices and then $\lfloor \boldsymbol{a} \times \rfloor = \lfloor \boldsymbol{b} \times \rfloor \Rightarrow \boldsymbol{a} = \boldsymbol{b}$ for $\boldsymbol{a}, \boldsymbol{b} \in \mathbb{R}^3$. 
Another property used is $\mathbf{R} \lfloor \boldsymbol{\theta} \times \rfloor \mathbf{R}^\top = \lfloor \mathbf{R} \boldsymbol{\theta} \times \rfloor$ for $\mathbf{R} \in SO(3)$.

**Comment by goldbattle** [comment]
You can refer to this technical report for mathematical identities you are trying to define:
http://mars.cs.umn.edu/tr/reports/Trawny05b.pdf

For the SO(3) ones, you I recommend Barfoot's book (specifically Section 7.1.5 and Equation 7.75):
http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf

In an old tech report I have some useful identities you can also check:
https://pgeneva.com/downloads/reports/tr_async.pdf
https://github.com/rpng/open_vins/files/10078528/useful_identities.pdf
