### ISSUE TITLE
Problem of the scale estimation

### ISSUE THREAD

**Issue by Immortal-lqx** [rpng/open_vins#113]
Hello, I tried open-vins with realsense d435i and realsense t265.
But no matter what camera I use, the scale estimation seems not very accurate. 
Sometimes I walked 5m away, but the /ov_msckf/poseimu shows that I had walked 8m or just 3m. 
Can anyone give any suggestion?

**Comment by WoosikLee2510** [comment]
How did you calibrate the cam, cam-imu calibration, and IMU noise?

**Comment by goldbattle** [comment]
This might also be due to poor focal length calibration and IMU noises.
Based on issue #102 there seems to be quite a few issues with the d435i.
