### ISSUE TITLE
Jacobian calculation for rotation only measurements. 

### ISSUE THREAD

**Issue by SubMishMar** [rpng/open_vins#122]
I went through your documentation and found that much of the derivations related to determination of expressions for Jacobians is associated to cases when the rotation matrix is multiplied to a vector (R v). I am particularly concerned about cases where we have sensors that provide rotation between time instants (in terms of a rotation matrix). I will be glad if you let me know if the equations and math I derive below look ok to you because I could not find any reference for this where all the details are provided at one place. 

Let us assume we have a sensor which provides the difference between two frames $\{i-1\}$ and $\{i\}$. Let's say the sensor provides it in terms of a rotation matrix $R^{i-1}_{i}$. Here the global frame of reference is $\{G\}$. So the measurement function can be written as:
![Screenshot from 2020-12-07 12-52-16](https://user-images.githubusercontent.com/28704031/101392217-16db1c00-388b-11eb-9ed2-c0c00b0c1ab0.png)

the LHS is the measurement and the RHS is composed of rotational state variables $R^{i-1}_{G}$ and $R^{i}_{G}$. The goal is to calculate the Jacobian of this measurement function with respect to the aforementioned state variables. 

For this, the rotation matrix can be perturbed as follows:
![Screenshot from 2020-12-07 12-53-12](https://user-images.githubusercontent.com/28704031/101392296-340fea80-388b-11eb-9598-9e87851d54d8.png)

Substituting and manipulating, one gets: 
![Screenshot from 2020-12-07 14-04-50](https://user-images.githubusercontent.com/28704031/101399555-3f681380-3895-11eb-9d58-ad71bdef9826.png)

Where: 
![Screenshot from 2020-12-07 12-54-37](https://user-images.githubusercontent.com/28704031/101392447-66b9e300-388b-11eb-86fc-f43caf2c524c.png)

Is it correct to say the measurement Jacobians with respect to the rotation state variables are:
![Screenshot from 2020-12-07 12-58-34](https://user-images.githubusercontent.com/28704031/101401572-2a40b400-3898-11eb-8f61-313829e04eee.png)

Appreciate your time and help :)

**Comment by goldbattle** [comment]
You need to define what your LHS error state is.
If the error for the LHS is R=exp(-theta)*R_hat, then I believe your derivations should be fine.

**Comment by SubMishMar** [comment]
Yes, that is what I define my error state as. Using the left multiplication with exp of a  -ve delta angle vector. Thanks for clarification.

**Comment by goldbattle** [comment]
You can have different measurement error defined (how you compute your residual, your LHS), then what your state error states. Thus you need to carefully define both of them (i.e. left or right orientation error states with positive negative signs).
