### ISSUE TITLE
[style] [format] Add clang-format and clang-tidy to the project

### ISSUE THREAD

**Issue by zgxsin** [rpng/open_vins#123]
Dear Maintainers,

Thanks for the great work you are doing. I just have some thought in my mind: It would be better to add clang-format and clang-tidy to the current project so that people can contribute to the current repo with the consistent code style. A template project with clang-tidy and and clang-format can be found here: https://github.com/lefticus/cpp_starter_project.

**Comment by goldbattle** [comment]
Has been added in 18c51c1895fc64c60d1082c54d1f73879fc7036f
