### ISSUE TITLE
Question: Run OpenVINS on Jetson TX2

### ISSUE THREAD

**Issue by TheRealKaufmann** [rpng/open_vins#128]
Hi there,
I really love the OpenVINS Project. 
But I have a Question: Is it possible to run OpenVINS on the Nvidia Jetson TX2. I'm not asking about implementation but I am wondering if the performance of the TX2 will be sufficient to run OpenVINS in realtime? 
Are there any specific reports regarding OpenVINS's CPU load?

Thanks!
Tom

**Comment by goldbattle** [comment]
Yes, I have run it at full frame rate (20-30fps as desired) if the set number of tracked features is 150-175 points. The important part to compile on other platforms is to ensure that you compile with platform specific optimization flags during build, but the TX2 should set those. If you are worried about the CPU usage, you can specify it to be single threaded and tune to that.

**Comment by TheRealKaufmann** [comment]
Thank you!
