### ISSUE TITLE
How to derive the orientation propagation equation?

### ISSUE THREAD

**Issue by niebayes** [rpng/open_vins#138]
I checked the IMU error state progation [page](https://docs.openvins.com/propagation.html#error_prop), but I got stuck in the derivation of oritentation propagation equation. In particular, it's this line that causes the confusion. 
<img width="780" alt="Screen Shot 2021-02-08 at 1 26 45 AM" src="https://user-images.githubusercontent.com/25320945/107154331-66ce8000-69ad-11eb-997c-171b8a257040.png">
I know the JPL convention is adoped and hence the minus signs in front of the skew-symmetric matrices. And I know the **exp** operator is actually the "vectorized" **Exp** operator which means it maps the rotation vector to the SO(3) Lie group. Also the composition of the nonimal state $$\hat{\omega}$$ and the error state $$\tilde{\omega}$$ gives the "true" state. 
But what places a minus sign in front of the omegas ? Due to local from/to global convertion or JPL convertion, or something else tricky?

**Comment by SubMishMar** [comment]
This thread https://github.com/rpng/open_vins/issues/112 might help you.

**Comment by goldbattle** [comment]
Does #112 address your issue?

**Comment by niebayes** [comment]
@goldbattle Yes, it's helpful!
