### ISSUE TITLE
How to integrate IMU intrinsics into the system?

### ISSUE THREAD

**Issue by niebayes** [rpng/open_vins#139]
I'm trying to integrate IMU intrinsics, i.e the misalignment error, scale error and g-sensitivity as shown in [Li's paper](https://intra.ece.ucr.edu/~mourikis/papers/Li2014ICRA.pdf), into openvins. As the paper shows, they're modeled as uncertain constants and parameterized as three matrices `T_g, T_a, T_s` which are then vectorized as a 27-length vector. As far as I'm concerned, they're not involved in the state propagation since they're not evolving. So I simply follow the error-state propagation scheme shown in [this page](https://docs.openvins.com/propagation.html#error_prop). However, I found that the rotational velocity error `\tilde{\omega}` cannot be derived from the same cancellation shown on that page, as the coefficients comprised of `T_g, T_a, T_s` cannot be simply factored out. 

I realized that there might be another route to derive the error state propagation, and I found [Shelly's thesis](https://vision.in.tum.de/_media/spezial/bib/shelley14msc.pdf) which uses first-order Taylor truncation to approximate the rotational velocity error by taking derivatives wrt. the states involved in rotational velocity measurements. 

On the other hand, I also found that the online IMU intrinsics calibration is not recommended for aerial and ground robots since there's typically at least one unobservable direction due to common motions, as stated in [Yang's paper](http://www.roboticsproceedings.org/rss16/p026.pdf). This paper also gives the equation of the linearized rotational velocity error despite with a different IMU intrinsic model which only has 15-dof.

Despite all these findings, I still cannot figure out how to integrate IMU intrinsics into openvins. Can someone give me some hints? And does it necessary to do so?

**Comment by goldbattle** [comment]
If you do this, then you will have a larger state transition matrix during propagation.
Even if they do not evolve with time (i.e. they do not evolve like the system biases), your integration is still a function of them.
You can apply the chainrule to find the derivative in respect to these correction terms.
