### ISSUE TITLE
noise in MSCKF-update

### ISSUE THREAD

**Issue by Wangxuefeng92** [rpng/open_vins#142]
Hi,
thanks for your project! I have a quastion: In MSCKF-update, why did you use R instead of  R_o(which is project to nullspace) in StateHelper::EKFUpdate() ?

**Comment by goldbattle** [comment]
As I believe mentioned in the original paper, since the noise is isotropic, the nullspace won't change the noise, thus we just create it after the fact. Hope this helps.
