### ISSUE TITLE
Testing OpenVins on planetary dataset

### ISSUE THREAD

**Issue by johanndiep** [rpng/open_vins#155]
For a research project at ESA I am trying to evaluate OpenVINS on martian-lookalike dataset gathered by a rover. Would be interesting to see how it performs versus other VO/SLAM algorithms.
The dataset contain stereoimages, angular velocity and linear acceleration measurements (https://robotics.estec.esa.int/datasets/katwijk-beach-11-2015/). 
The angular velocity and linear acceleration data are logged in txt-files. Furthermore, the intrinsic parameters of the camera are available. The transformation from IMU to camera frame is also known. 

I am not very familiar with ROS hence I am glad if someone can give me couple of hints how to run OpenVINS on my dataset. Specifically, if it is necessary to transform my dataset into "rosbags" in order to run the software via "launchfiles".

**Comment by goldbattle** [comment]
You might want to checkout the Kalibr bag creator, or make one specific to the dataset:
https://github.com/ethz-asl/kalibr/wiki/bag-format
https://github.com/ethz-asl/kalibr/blob/master/aslam_offline_calibration/kalibr/python/kalibr_bagcreater
