### ISSUE TITLE
loop through SLAM features 

### ISSUE THREAD

**Issue by pzhu008** [rpng/open_vins#16]
Hi, when loop through current SLAM features and grab them for update, is that possible "feats_slam" already has "feat2" from "feats_maxtracks" ? If so, "feat2" will be double used ?

VioManager.cpp (line 599-607 )
 if(feat2 != nullptr) feats_slam.push_back(feat2);

**Comment by goldbattle** [comment]
SLAM features will never be in the max track unless we have skipped updating for a whole window, which we never do. Using the [cleanup()](https://docs.openvins.com/classov__core_1_1FeatureDatabase.html#a81c64036a8e8a8f2dc00a88f55a8579f) function after update removes the SLAM features from the tracking database after update, so at the next timestep only the newest frame track will be there (so the number of measurements is of size one). Thus the SLAM feature will never be in the maxtracks vector, so we need to ask the database if it has a measurement that has tracked into this new frame.
