### ISSUE TITLE
realsense d435i with tx2

### ISSUE THREAD

**Issue by vislero** [rpng/open_vins#161]
Hello.

First of all, Thank you for your great working .

We experimented Open VINS on a Jetson TX2 using the Intel Realsense D-435i.

We are testing Open VINS for the Drone's Position Flight.

By the way, when we tested Open VINS last year (in commit f56cac358509226074f5fbe0d956001464006d34), the pose tracking is working well.
![1](https://user-images.githubusercontent.com/69630044/114832425-6d440280-9e09-11eb-9726-2306174e35ad.png)

But when we tested Open VINS in recent commit (in commit e516f7c564c2159b7edfb42a8230b732bf6aebc2),  pose  tracking is more drift aware (especially when device is frozen).

![Screenshot from 2021-04-15 16-38-10](https://user-images.githubusercontent.com/69630044/114832429-6ddc9900-9e09-11eb-83a7-a727f1ec94f5.png)

like below image In Current Depth image, reprojected points are diverged. 

![Screenshot from 2021-04-15 16-40-00](https://user-images.githubusercontent.com/69630044/114832432-6e752f80-9e09-11eb-8cd4-d5fa38b42508.png)
Below is our launch file URL of open vins 
[https://gist.github.com/vislero/9aeb297d2cc63423fe7089a16309aff7]

What is the main difference between two version? 

And when we turned on the 'zupt' mode in launch script. the 'zupt' module is working not perfectly. How to adjust the parameters to work fine ?

Thanks.

Regards.

**Comment by goldbattle** [comment]
It is tough to pick a threshold for the zero velocity update. If you are using SLAM features (it looks like you are), you can likely get away with not using the zero velocity update at all. The update will work better with a higher quality IMU, so I am not sure if the d435i will give reasonable results or not (have never used myself).

I assume the issue is that when you place the unit down it is flying away?
Are you getting any SLAM feature updates during this time?

**Comment by vislero** [comment]
Yes, I thought so.

When i stop moving d435.

The reprojected points are flying away like in the gif picture below.
![openvins_drift2](https://user-images.githubusercontent.com/69630044/115857175-53896780-a468-11eb-8b84-fc1bbb5fcb89.gif)

And, it seems that the SLAM feature has been updated during this period.

What is the problem?

As mentioned earlier, it works perfectly in Oepn VINS v.2.2 using the same launch file (parameters).
launch file : (https://gist.github.com/vislero/9aeb297d2cc63423fe7089a16309aff7)

Thank you.

**Comment by goldbattle** [comment]
Can you possibly upload a bag for me to debug with in the upcoming week?
This shouldn't be the case, so I am not sure if there was a regression.

**Comment by vislero** [comment]
Hello @goldbattle 

we uploaded the bag file in below url.

[rosbag_file](https://uvify-my.sharepoint.com/:u:/p/daehyun_hwang/EYJIYwzHzR1Jq7gR3c2fO0UBsWJ7QIVE_pNMQLHDyiFj6g?e=VO4fmH)

Thank you !

**Comment by goldbattle** [comment]
![image](https://user-images.githubusercontent.com/2222562/122827021-dcc6ea00-d2b1-11eb-981c-92950dce6a8a.png)

It seems to work out of the box on the bag you sent.
I just pushed some new zero velocity detection code which uses the image disparity now so you might want to test that.
https://gist.github.com/goldbattle/38633c3ccc813787b480f65c80df1661

**Comment by vislero** [comment]
![vio_performance_openvins](https://user-images.githubusercontent.com/69630044/122890450-a6a36c00-d37e-11eb-93ea-887965abce8a.gif)

That's a great performance ! 

Now, reprojected points are not diverged in current depth view.

Thank you very much.

By the way, when we tested the open vins, the pose estimated in the initialization phase diverges a few times. 

and how to fine tune the parameters about the zero velocity detection?

**Comment by vislero** [comment]
Sorry. We had not updated Open VINS.

Updating the latest version of Open VINS solved all problems

Now close this issue.

Thank you very much so far.

**Comment by Majed-Alsubaie** [comment]
Hi, @vislero 
I would like to ask how did you calibrate the d435i ? did you use official Realsensce calibration tool ?

Hi @goldbattle ,
I am planning to integrate Openvins with real drone , Do you have any advice , guided , certain test to check before first flight  ?
+ Did you try to use OpenVins with Rtabmap ? any issues with it ?

**Comment by vislero** [comment]
I used Kalibr to calibrate intrinsic, extrinsic parameters of d435i.

**Comment by ClementLASSENA** [comment]
Hi @vislero,
Does your configuration (d435 + open_vins) work in mono?
Indeed, I am trying to set a similar configuration but I am not sure that the mono-MSCKF can converge with this type of consumer grade IMU.

**Comment by mzahana** [comment]
Hi @vislero 

Where you able to use `open_vins` in flight ?

I am trying to set it up on a drone usgin Jetson Orin NX ad Realsense D455 camera.

I face issues during the initialization of the filter. What parameters did you use in the `estimator_config.yaml`?

**Comment by lesliennz** [comment]
> I used Kalibr to calibrate intrinsic, extrinsic parameters of d435i.

**Comment by lesliennz** [comment]
> ![vio_performance_openvins](https://user-images.githubusercontent.com/69630044/122890450-a6a36c00-d37e-11eb-93ea-887965abce8a.gif) [ ![vio_performance_openvins](https://user-images.githubusercontent.com/69630044/122890450-a6a36c00-d37e-11eb-93ea-887965abce8a.gif) ](https://user-images.githubusercontent.com/69630044/122890450-a6a36c00-d37e-11eb-93ea-887965abce8a.gif) [ ](https://user-images.githubusercontent.com/69630044/122890450-a6a36c00-d37e-11eb-93ea-887965abce8a.gif)
> 
> That's a great performance !
> 
> Now, reprojected points not diverge in current depth view.
> 
> Thank you very much.
> 
> By the way, Sometimes the pose estimated in the initialization phase diverge. Do you have some tips for robust initialization?
> 
> And, in a stationary situation, when I turned on the zupt module and started openvins, the poses diverge. How to fine tune the parameters about the zero velocity detection?

Hello, may I ask if you can provide the value of your initialization parameters? I am also using d435i, but it can not be well refined initialization, which is the following parameters:
init_window_time:
init_imu_thresh
init_max_disparity
init_max_features
Thank you so much.
