### ISSUE TITLE
Possible bug in parameters to `perform_griding`?

### ISSUE THREAD

**Issue by charmoniumQ** [rpng/open_vins#166]
At [`ov_core/src/track/TrackKLT.cpp:532`](https://github.com/rpng/open_vins/blob/master/ov_core/src/track/TrackKLT.cpp#L532), you call:

```
Grider_FAST::perform_griding(img1pyr.at(0), pts1_ext, num_features, num_featsneeded_1, grid_x, grid_y, threshold, true)
```

where `num_features` is an `int`.

But `Grider_FAST::perform_griding` is defined at [`ov_core/src/track/Grider_FAST.h:L94`](https://github.com/rpng/open_vins/blob/master/ov_core/src/track/Grider_FAST.h#L94) as:

```
void perform_griding(const cv::Mat&, std::vector<cv::KeyPoint>&, bool, int, int, int, int, bool)
```

`num_features` is implicitly coerced into a boolean; the one which determines if griding is performed with multiple threads. Is this a mistake or is it intentional?

**Comment by goldbattle** [comment]
Should be fixed, I did see some randomness which I made a small note:
https://github.com/rpng/open_vins/blob/master/ov_core/src/track/TrackKLT.cpp#L366-L379
```
// NOTE: if we multi-thread this atomic can cause some randomness due to multiple thread detecting features
// NOTE: this is due to the fact that we select update features based on feat id
// NOTE: thus the order will matter since we try to select oldest (smallest id) to update with
// NOTE: not sure how to remove... maybe a better way?
```
