### ISSUE TITLE
Could you sharing the detail information about online intrinsic camera calibration  

### ISSUE THREAD

**Issue by arenas7307979** [rpng/open_vins#169]
Thanks for sharing! That's an awesome work
Could you introduce the cost function, Jacobin, and optimization process for online camera intrinsic calibration?

**Comment by goldbattle** [comment]
I recommend you read the paper and documentation.
http://udel.edu/~pgeneva/downloads/papers/c10.pdf
https://docs.openvins.com/update-feat.html#distortion

**Comment by arenas7307979** [comment]
Thank you for your reply.

**Comment by arenas7307979** [comment]
hii, 
I found a difference between the document and  code, 
code :  (2 * cam_d(4) * x_2 + 4 * cam_d(5) * x_2 * r)
document: 2 * p1 * xn^2 + 4 * k2  * xn^2  *（xn^2 + yn^2) 
Should I change **r** to **r squared**？

![image](https://user-images.githubusercontent.com/5019568/123251222-8827a700-d51d-11eb-97d1-a1a5ea9036c0.png)


![image](https://user-images.githubusercontent.com/5019568/123251396-bc9b6300-d51d-11eb-9eca-fed29a1b86ea.png)


![image](https://user-images.githubusercontent.com/5019568/123251335-aa212980-d51d-11eb-93f1-8f1d7a86663f.png)

**Comment by goldbattle** [comment]
Thanks, documentation is correct. Will correct in an upcoming commit.
