### ISSUE TITLE
Does open VINS contain loop closure?

### ISSUE THREAD

**Issue by apache8080** [rpng/open_vins#17]
Many msckf VIO implementations on github don't contain loop closure so they can't be used as a true SLAM implementation. I was wondering if open VINS contained loop closure.

**Comment by goldbattle** [comment]
Current we support "temporal" slam features, which are marginalized out as soon as they are lost from view. In the case that you are in a small area this can prevent drift if features are able to be tracked for a long period of time. There isn't a secondary loop closure thread as we focused on purely the accuracy of VIO. Adding a simple secondary thread on the [roadmap](https://docs.openvins.com/dev-roadmap.html), but no set timeline.
