### ISSUE TITLE
slam feature management bug ?

### ISSUE THREAD

**Issue by tadashi-hamada196** [rpng/open_vins#173]
Hi, the funchtion do_feature_propagate_update in the file VioManager.cpp may have bug, you delete slam feature observation after slam feature update. when using ANCHORED_INVERSE_DEPTH_SINGLE representation, slam feature need being observed twice before  using in slam update, if slam observation being remove here, it will never to be observed twice,  which means slam feature cannot be updated after it being add to states.

**Comment by goldbattle** [comment]
Yes I believe there is a PR mention this (#170).
