### ISSUE TITLE
Sign of gravity vector

### ISSUE THREAD

**Issue by stefangachter** [rpng/open_vins#174]
I have a more subtle issue with the gravity vector sign definition in the IMU propagation derivations https://docs.openvins.com/propagation.html
The equation for the accelerometer states
![image](https://user-images.githubusercontent.com/7974580/122067207-adb50200-cdf3-11eb-976c-5d20b3c761fe.png)
that is specific force as measured by the IMU is equal to acceleration of the IMU plus gravity plus bias plus noise.
According to Newton's second law of motion, the sum of all specific forces is equal to the acceleration. In my understanding, gravity is a mass specific force. Thus, the equation should be 
![image](https://user-images.githubusercontent.com/7974580/122066886-6a5a9380-cdf3-11eb-874b-da9bada0bd95.png)
or rearranged
![image](https://user-images.githubusercontent.com/7974580/122066998-7f372700-cdf3-11eb-9044-633fb1c49693.png)
Thus, the sign of gravity vector should be negative.

**Comment by goldbattle** [comment]
You can define it any way you want as long as you are consistent.

**Comment by stefangachter** [comment]
Sure, you can define it as long as you are consistent. Personally, I find it confusing this way.
An IMU cannot measure gravity, only the reaction force due to gravity. Assume a bias- and noise-free IMU at rest with its z-axis pointing upwards, then acceleration is zero and the equation results
![image](https://user-images.githubusercontent.com/7974580/122158861-9c104080-ce6d-11eb-8393-fbeb1fdb6432.png)
The IMU readings are about 9.81m/s^2 and positive, because it is measuring the reaction force not gravity. The gravity vector is expected to point downwards to earth center. This is not reflected in this equation.

**Comment by goldbattle** [comment]
The frame {I} is the local IMU frame, not the global frame. You can define gravity going up or down, and you will just have a flipped local frame. For example the ENU vs the NED frames in GPS inertial systems. Here we present it in a "measurement model" way, thus we have the raw reading, being equal to some values (true, gravity, bias, and noise).

You might also check out some comments in the gtsam project:
https://github.com/borglab/gtsam/blob/329e70e33d7d79546952e91c7d965ab244be4185/gtsam/navigation/CombinedImuFactor.h#L80-L88
https://github.com/borglab/gtsam/blob/2c5be4de19362ada218bb476700a96ba75bf1d77/gtsam/navigation/GPSFactor.h#L26-L34
```
Z-down navigation frame, such as NED: gravity points along positive Z-axis
Z-up navigation frame, such as ENU: gravity points along negative Z-axis
```

**Comment by stefangachter** [comment]
Thanks for the information. 

It is one thing what the IMU is measuring - only specific forces - and another thing how to choose the global frame. The global frame can be chosen independent of the IMU. If ENU or NED does not matter. Probably we agree on that. I understand that you are using a "measurement model". My point is that IMU can measure gravity only as a reaction force.

Any major text book of inertial navigation - for example Jekeli, Inertial Navigation Systems with Geodetic Applications or Groves, Principles of GNSS, Inertial, and Multisensor Integrated Navigation Systems - have a lengthy section on these laws and conventions. And these text books end up with a negative sign for the gravity. 

Using a "measurement model" is fine, but can get confusing when taking a look at the actual IMU readings. That is my experience, but maybe it is my limited understanding.
