### ISSUE TITLE
Camera Extrinsic  

### ISSUE THREAD

**Issue by Hughbyun** [rpng/open_vins#176]
Hi,
 
I am just wondering about the camera extrinsic. 

For the parameter T_C0toI, I put the transformation matrix from the camera frame to IMU. 
And I also tried with the parameters from VINS-fusion, which is from IMU to the camera frame.  
However, it shows better pose estimation when I use the param from VINS which is also showing differences in feature detection as can be seen in the pictures below. I am using the same value except camera extrinsic. 

- T_C0toI
![C0toI](https://user-images.githubusercontent.com/64269877/122575005-9eec7a80-d093-11eb-8f28-8c4bb5fa6299.jpg)

- body_T_cam0
![ItoC0](https://user-images.githubusercontent.com/64269877/122575022-a6138880-d093-11eb-8346-cd7242c8f375.jpg)

Which one is the right camera extrinsic to put for OpenVINS?
Looking forward to hearing from you. 
Thanks.

**Comment by goldbattle** [comment]
OpenVINS uses T_C0toI which means it contains the rotation from CAM0 to IMU (R_C0toI) and the position of the CAM0 in the IMU frame (p_C0inI). I believe we use the same transformation as VINS-Mono (if my memory is correct, you can compare the eth/euroc configs). So you might have misunderstood the variable naming of VINS-Mono which is a bit confusing.

For ours see this:
https://docs.openvins.com/dev-coding-style.html#coding-style-naming

**Comment by Hughbyun** [comment]
Thanks for the feedback. 
Then I am sure I misunderstood the variable naming. 
I should have compared the configs, sorry for bothering you. 
Thanks again.

**Comment by goldbattle** [comment]
No worries, glad to help. You can always try disabling online calibration as the system should still run with reasonable values, but if you flip the extrinsic by accident then it will normally diverge / fly away instantly.

**Comment by Hughbyun** [comment]
Hi @goldbattle, 

Sorry to bother you again. 
Just wondering about the Schmidt-MSCKF. Are you planning to open-source for S-MSCKF, too?
Thanks. Looking forward to hearing from you.

**Comment by goldbattle** [comment]
Not at this time, down the line maybe.
