### ISSUE TITLE
A problem when I try to add GPS measurement update in open_vins

### ISSUE THREAD

**Issue by xhy3054** [rpng/open_vins#179]
Hello, the covariance of vio will fly away soon, when I try to add GPS measurement update in open_vins. Do you have any suggestions if you have experience in similar work? The residual and jacobian of GPS measurement refers to your article "Intermittent GPS-aided VIO: Online Initialization and Calibration".(I have checked many times for the derivation of jacobian, but I can't find where wrong... so do you think where else should extra attention be paid? )

**Comment by goldbattle** [comment]
Thanks for taking a look at the project. GPS fusion is not a part of this codebase, so I recommend you debug that on your own. The paper you mentioned does cover the necessary background on the problem. I recommend you first test with the simulator with known calibration and ENU-VIO sensor frame and then move on from there. Best of luck!
