### ISSUE TITLE
feature tracking

### ISSUE THREAD

**Issue by pzhu008** [rpng/open_vins#18]
hi,

It seem that lots of features are **featsup_MSCKF**, but only few of them will be the good_features_msckf. Most of the features will be rejected by "ct_meas < 3"
When using descriptor and only doing msckf,  only about 1/5 features will be used. Most of the "feats_lost" have the length less than 3. is this nomal?

**Comment by goldbattle** [comment]
We only want to use good quality tracks that have a high quality pFinG estimate to linearize at, thus we want at least 3 measurements of it. I think we can be even more strict with this to ensure that we have enough measurements for feature triangulation, but have not really investigated that much. When using the descriptor tracking we extract a lot more features (500 for desc vs. 150 for KLT) as the frontend is very strict in its rejection during matching giving very short lived tracks.
