### ISSUE TITLE
question for test_tracking.cpp

### ISSUE THREAD

**Issue by linzha0** [rpng/open_vins#180]
Hi, thanks for this awesome project. I am looking at test_tracking.cpp to test tracking features. I am little confused at [test_tracking.cpp - Line 118](https://github.com/rpng/open_vins/blob/master/ov_core/src/test_tracking.cpp#L118). It seems like  undistorted points are used for ransac to reject outliers. But in the test, it just use fake camera info. 

Thanks for your help.

**Comment by goldbattle** [comment]
It is just a test for the tracking, in practice we set the camera info to ensure better ransac performance.
You can take a look in ov_msckf to see how it is actually used.
