### ISSUE TITLE
Zero velocity update jacobian

### ISSUE THREAD

**Issue by aserbremen** [rpng/open_vins#182]
First off, thanks for providing this well structured VINS-platform. 

I have a question concerning the measurement jacobians for the Zero Velocity Update discussed on this [page](https://docs.openvins.com/update-zerovelocity.html). 

Shouldn't the Jacobians of the error measurement function 
![image](https://user-images.githubusercontent.com/56029245/124144995-bb71b500-da8c-11eb-80cc-1b070a42bca1.png)
w.r.t. the biases be the positive Identity <img src="https://render.githubusercontent.com/render/math?math=I_{3\times3}"> and not negative identity.

![image](https://user-images.githubusercontent.com/56029245/124144373-2ff82400-da8c-11eb-9b83-59bb5fcf2396.png)

Am i missing something here?

**Comment by goldbattle** [comment]
The actual measurement function we take the derivative of is the following:
![image](https://user-images.githubusercontent.com/2222562/124612772-9ab8af00-de40-11eb-8657-939e922fae88.png)

Here we say that a and w are known to be zero and are the "measurement" for the zero velocity update.
The picture you posted is just what the residual is evaluated as.
