### ISSUE TITLE
Support Panoramic / 360deg Camera Models

### ISSUE THREAD

**Issue by NightNightNight** [rpng/open_vins#184]
Does open_vins support panoramic camera like Ricoh or insta360 or not?

**Comment by goldbattle** [comment]
As per https://github.com/rpng/open_vins/issues/131 we still don't. I believe the main issue is that these cameras are no longer pinhole cameras, thus need a different triangulation and projection models. It might be something we should support in the future if there is enough interest.

Do you have links to what drivers / exact cameras you were planning on using?
Do they come with IMU, or do you need to attach it as an additional sensor?

**Comment by NightNightNight** [comment]
https://www.insta360.com/cn/product/insta360-onex/

**Comment by NightNightNight** [comment]
we used Ricoh camera without IMU. Now we will use insta360 with IMU.  [https://www.insta360.com/cn/product/insta360-onex/](url)

**Comment by CanCanZeng** [comment]
Hi @NightNightNight , how do you extract imu data from insv file produced by insta360 device?
As I have tested, gopro max is better to do vio, since it has done much things to remove rolling shutter effect and stitch effect. And they provide an open source project https://github.com/gopro/gpmf-parser to extract meta data(imu and gps) from their video. Insta360 produces more visual appealing video, but is seems not very good for geometrical machine vision task.

**Comment by goldbattle** [comment]
Closing this since it isn't something that we plan to add at this point (someone can fork and implement if they are interested).

**Comment by XUTONG1024** [comment]
> Does open_vins support panoramic camera like Ricoh or insta360 or not?

May I ask if you have made any progress on this issue? I am currently considering using the built-in IMU of Insta360 x2 to implement vio. Can you give me some suggestions?

**Comment by XUTONG1024** [comment]
> Hi @NightNightNight , how do you extract imu data from insv file produced by insta360 device? As I have tested, gopro max is better to do vio, since it has done much things to remove rolling shutter effect and stitch effect. And they provide an open source project https://github.com/gopro/gpmf-parser to extract meta data(imu and gps) from their video. Insta360 produces more visual appealing video, but is seems not very good for geometrical machine vision task.

May I ask if you have made any progress on this issue? I am currently considering using the built-in IMU of Insta360 x2 to implement vio. Can you give me some suggestions?
