### ISSUE TITLE
Unable to Record Trajectory to File

### ISSUE THREAD

**Issue by chenyong1003** [rpng/open_vins#185]

**Comment by chenyong1003** [comment]
[ZUPT]: failed disparity (1.071 > 0.500, 332 features)
[ZUPT]: rejected |v_IinG| = 0.010 (chi2 170.722 > 0.000)
[TIME]: 0.0100 seconds for tracking
[TIME]: 0.0009 seconds for propagation
[TIME]: 0.0001 seconds for MSCKF update (0 feats)
[TIME]: 0.0076 seconds for SLAM update (65 feats)
[TIME]: 0.0008 seconds for SLAM delayed init (0 feats)
[TIME]: 0.0025 seconds for re-tri & marg (11 clones in state)
[TIME]: 0.0218 seconds for total (camera 0 1)
q_GtoI = 0.816,-0.053,0.574,0.045 | p_IinG = -0.349,0.000,0.090 | dist = 78.39 (meters)
bg = -0.0015,0.0152,0.0785 | ba = -0.0178,0.1781,-0.0022
camera-imu timeoffset = -0.00020
cam0 intrinsics = 458.520,458.541,364.830,246.228 | -0.277,0.068,0.000,-0.000
cam1 intrinsics = 456.793,456.730,377.821,252.999 | -0.277,0.069,-0.000,0.000
cam0 extrinsics = -0.005,0.009,0.702,0.712 | 0.069,-0.011,0.008
cam1 extrinsics = -0.000,0.014,0.702,0.712 | -0.041,-0.009,0.003
[TIME]: 0.0016 seconds for visualization
================================================================================REQUIRED process [rosbag-2] has died!
process has finished cleanly
log file: /home/c/.ros/log/fb4126b6-e3d3-11eb-8efc-000c2941d447/rosbag-2*.log
Initiating shutdown!
================================================================================
[rosbag-2] killing on exit
[run_subscribe_msckf-1] killing on exit
camera-imu timeoffset = -0.00020

cam0 intrinsics:
458.520,458.541,364.830,246.228
-0.27682,0.06801,0.00013,-0.00002

cam1 intrinsics:
456.793,456.730,377.821,252.999
-0.27749,0.06897,-0.00019,0.00004

T_C0toI:
0.015,-1.000,0.006,-0.012,
1.000,0.015,0.020,-0.069,
-0.020,0.006,1.000,-0.007,
0.000,0.000,0.000,1.000

T_C1toI:
0.013,-1.000,0.019,-0.008,
1.000,0.013,0.020,0.041,
-0.020,0.019,1.000,-0.004,
0.000,0.000,0.000,1.000

TIME: 108.892 seconds

terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
shutting down processing monitor...
... shutting down processing monitor complete
done
The above error occurred in the running .can you tell me what the problem is？Thank you very much！

**Comment by goldbattle** [comment]
It looks like it ran fine, see that the process finished cleanly.

**Comment by chenyong1003** [comment]
Thank you for response！I use the launch file below: https://github.com/rpng/open_vins/blob/master/ov_msckf/launch/pgeneva_ros_eth.launch. The above description appears when it runs,and the corresponding file isn’t generated in the corresponding folder.I reinstalled all the software,but nothing worked out.

**Comment by goldbattle** [comment]
What corresponding file? You should be able to see everything in RVIZ, use the config file in the ov_msckf/launch/ folder for that.

**Comment by chenyong1003** [comment]
When the program finished,the save track path wasn’t generated in the specified folder tmp.

**Comment by goldbattle** [comment]
I recommend you check permissions and that the folder is already created.
Are there any error logs from the `pose_to_file` in the console?
Are you able to visualize everything in RVIZ ok?
I assume you have enabled the param to record to file correct?

**Comment by chenyong1003** [comment]
Can you elaborate on the error log？After I reinstalled the system,RVIZ wasn’t displayed.Then I added it according to the original one, and now it can be displayed. It wiil be the same after I finish running, [run_subscribe_msckf-1]killing on exit and [rosbag-2]killing on exit will be displayed on the terminal.

**Comment by goldbattle** [comment]
There was no error in what you posted, can you provide a bit more detail on the issue?

**Comment by chenyong1003** [comment]
![9DBEC68D-E415-4FB5-AE25-EF27A2C678F4](https://user-images.githubusercontent.com/87304070/125879773-c7af7830-62bb-4d98-88bf-20e055781587.png)
![6D03887F-BE0D-420A-A252-559A67400755](https://user-images.githubusercontent.com/87304070/125879784-80a7cf16-adb2-49c5-82fc-19145c294589.png)
![DB72CD48-362E-4B1E-B74A-B9DAE5D04D72](https://user-images.githubusercontent.com/87304070/125879789-e084c836-a7f5-4466-baee-fa037d711a6c.png)
This is the picture taken after I just finished running. Is there anything else to add？

**Comment by goldbattle** [comment]
Have you set the dosave to true? You can also try saving to another folder.

**Comment by chenyong1003** [comment]
Thank you very much for you reply！now the track can be saved,but the terminal still shows [rosbag-2]and[run_subscribe_msckf-1]killing on exit.

**Comment by goldbattle** [comment]
Glad we got it working. The rosbag will terminate once it finishes playing the complete bag.
