### ISSUE TITLE
Gravity in the global frame 

### ISSUE THREAD

**Issue by rakshith95** [rpng/open_vins#187]
Hello, does the 'gravity' parameter depend on the axes of the IMU, or only the 'world' frame? The documentation says "Gravity in the global frame (i.e. should be [0, 0, 9.81] typically)"; and these are my world, and IMU frames.  ![IMU world](https://user-images.githubusercontent.com/33649411/125676903-4a2eb438-d451-48a3-bc4e-d966c647d548.png) 

Since the world frame has the gravity along the Z axis, I assume it must be defined as [0,0,9.81], but I wonder if it should differ since my IMU has the -Y axis

**Comment by WoosikLee2510** [comment]
Hi. Are you using IMU with NED coordinate? In that case, I saw no problem blindly using the system as it is, except that the trajectory was flipped.

**Comment by rakshith95** [comment]
Hi, the IMU does not follow the NED coordinate system.  It is similar to the OpenCV system where the Z axis protrudes out, + Y axis is towards the ground, and X axis  to the right

**Comment by rakshith95** [comment]
Hi, the IMU does not follow the NED coordinate system.  It is similar to the OpenCV system where the Z axis protrudes out, + Y axis is towards the ground, and X axis  to the right

**Comment by rakshith95** [comment]
Hi, the IMU does not follow the NED coordinate system.  It is similar to the OpenCV system where the Z axis protrudes out, + Y axis is towards the ground, and X axis  to the right

**Comment by WoosikLee2510** [comment]
If it is just how you posed the imu, then it should be fine.

**Comment by rakshith95** [comment]
Alright, thank you. Can you tell me when it would be different?

**Comment by WoosikLee2510** [comment]
I hope my previous (edited) comment helps?

**Comment by rakshith95** [comment]
Yes it does, thank you. Closing this.
