### ISSUE TITLE
Does VioManager::get_state() give the current pose estimated after SLAM?

### ISSUE THREAD

**Issue by apache8080** [rpng/open_vins#20]
I am trying to get the current estimated pose while open_vins SLAM is running. Would the VioManager::get_state() be the function I want to use? I basically just want the final translation and rotation that is estimated by the system.

**Comment by goldbattle** [comment]
You can check out the ros publisher:
https://github.com/rpng/open_vins/blob/master/ov_msckf/src/core/RosVisualizer.cpp#L170-L196

What we publish is the rotation from the global frame to the imu and position of the imu in the global. If you use the `get_state` function then you will need to access the imu object which has the current estimate at the state timestep.
