### ISSUE TITLE
serial reader rosbag segmentation fault munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by ilms123** [rpng/open_vins#208]
Hi,
   I have  a problem of roslaunch. When I run "**`roslaunch ov_msckf pgeneva_ros_eth.launch`**”, the program runs well.
But it failed when run "**`roslaunch ov_msckf pgeneva_serial_eth.launch`**".  
The error shows 
![111](https://user-images.githubusercontent.com/42759203/144417989-b1c6c2b1-da40-4a27-bcc2-87e95f7aaf0e.png)

My Configuration information：ROS noetic   \ python 3.8 (the same problem using python 2.7) \  ubuntu 20.04

Thank you ! Looking forward your reply!

**Comment by WoosikLee2510** [comment]
can you try running gdb (its in the launch file) and repost the error please?

**Comment by ilms123** [comment]
I try to running gdb ,it shows 
![微信截图_20211206105806](https://user-images.githubusercontent.com/42759203/144780047-6dbc9bc2-d974-45b8-a40b-9c37bdf18075.png)
But when I debug it in my another computer ,it run well. It have the same configuration information:ROS noetic \ python 3.8  \ ubuntu 20.04 
Is it the problem with system configuration? Do I need to reinstall Ros or ubuntu ?

**Comment by goldbattle** [comment]
Yeah, this looks like either it is linking to a wrong version of ROS, there is some issue with your ROS install, or the bad is corrupted. You could try reinstalling ros, rebuilding from a clean workspace, and using the subscriber node. Do you only have one version of ROS installed on your system?

**Comment by ilms123** [comment]
I only have one version of ROS noetic on my system, and reinstall it correctly. I rebuild a new workspace and debug it .Subscriber node runs well ,serial node shows same error . Maybe it is the problem of  compatibility of application . Weird

**Comment by goldbattle** [comment]
I would recommend trying with another bag, otherwise not sure if there is anything from my side to help with.

**Comment by ilms123** [comment]
I will use another bag . Thanks a lot !!!
