### ISSUE TITLE
Using the simulator

### ISSUE THREAD

**Issue by jcremona** [rpng/open_vins#228]
Thanks to the authors for releasing this very interesting work. I would like to ask if the simulator can be used to evaluate other VIO systems. I could not find any information on this in the documentation. Thank you.

**Comment by WoosikLee2510** [comment]
Simple answer: Yes.
The simulator simulates both ground truth (true measurements, true state, etc) and noisy measurements. Thus you can use our simulator to generate the measurements for other VIO systems (or record them in the bag) and test them.
