### ISSUE TITLE
Confusion regarding IMU Orientation Error Propagation

### ISSUE THREAD

**Issue by mateicodrul** [rpng/open_vins#251]
Hello,

I have some questions regarding the orientation error propagation in discrete time for the IMU. In the documentation, you write the following:

![imu_1](https://user-images.githubusercontent.com/48459092/168126540-ff93e7ab-7d5f-4409-bee0-5ffc9c49693a.png)

My first question concerns the line:

![imu_2](https://user-images.githubusercontent.com/48459092/168127540-1c49f846-23f7-42e5-8d44-c2dd28f07e9a.png)

Why do we write the rotation from I_{k} to I_{k+1} as an exponential instead of using the small angle approximation, as we do for the rotation from G to I_{k}? Is writing this exponential (and later expressing it using the right Jacobian) simply a better approximation and that is why we do it?

Secondly, on the next line

![imu_3](https://user-images.githubusercontent.com/48459092/168127951-14d0bec2-3f71-4a0b-b533-2d834e14879f.png)

we separate the exponential and use the right Jacobian, but is the separation correct? Shouldn't the order in which we write the 2 exponentials be reversed, since we use the global-to-local rotation convention (as we actually state on the very first line in the first picture)? It seems to me that the effect the right Jacobian has must be expressed in frame I_{k+1}. That means, it must be applied to the left of the mean rotation from I_{k} to I_{k+1}, not to the right. 

Thank you very much in advance!

Edit: Additionally, perhaps you would be so kind as to clarify the meaning of the vector theta. Is the associated angle defined from the frame at the bottom index to the frame at the top index (e.g.: from G to I, in the first line of the first picture), or the other way around? If the bottom to top convention is used (which was my guess), then it seems to me you forgot one minus in the argument of J_r in the following:

![imu_5](https://user-images.githubusercontent.com/48459092/168258825-690d0d3a-d0a5-46d3-b500-28aaa3f4ae32.png)

because the original argument of J_r in the previous equation had a negative sign (please see below)

![imu_4](https://user-images.githubusercontent.com/48459092/168259266-ac5c4751-df78-43a7-b633-c8ca06ee463c.png)

**Comment by goldbattle** [comment]
Sorry for not responding, as I was at a conference. I can formulate a more detail response when I find time, but I think I can point you towards the book that can help you clarify your understanding of rotations.

> State Estimation for Robotics by Timothy D. Barfoot
> http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17.pdf

Specifically equation 7.75 for how we use Jr / Jl.
![image](https://user-images.githubusercontent.com/2222562/171737096-6fc4de03-85ee-4bef-9c3c-aaaa8e65a124.png)


In the first equation you posted, we are doing *two perturbations* in respect to some omega_tilda and on the G to I_{k} rotation. These are not equal as you pointed out as one perturbation is in the tangent space of the Lie group, while the other we are perturbing by a multiplicative error `exp(delta_theta)*exp(theta)` does not equal `exp(delta_theta+theta)` (this is a key property of Lie groups).

We perturb in the tangent space as we want to compute the error in respect the the angular velocity white noise, and bias bg that is inside the exponential. This means the actual error is in the tangent space here.

As for your edited question the definition of theta. For SO(3) the theta is the negative of the angle you want to rotate. So if you want to rotate 30 degrees, the matrix will be R = exp(-30). You can try this out in 2d to prove why this is the case. Thus the theta_IktoIk+1 will be the angular velocity time DT negated. Hope this helps.
