### ISSUE TITLE
Does there exist an more detailed explanation on the zero velocity detection in theory?

### ISSUE THREAD

**Issue by ze-ta** [rpng/open_vins#252]
Hi, guys! Why do you use the following condition to see if we are current at zero velocity?
$$\tilde{\mathbf{z}}^T (\mathbf{H} \mathbf{P} \mathbf{H}^T + \alpha \mathbf{R})^{-1} < \chi^2$$
What does $\mathbf{H},\mathbf{P},\mathbf{R}$ means? Does there exist an detailed explanation or reference?

**Comment by goldbattle** [comment]
The wiki page has some details and references if you are still interested:
https://docs.openvins.com/update-zerovelocity.html
