### ISSUE TITLE
No rule to make target '/usr/local/cuda-10.2/lib64/libcudart_static.a'

### ISSUE THREAD

**Issue by manthan99** [rpng/open_vins#265]
Hi

I am trying to build on ROS-1 Noetic (Ubuntu 20.04) and getting the following error for the ov_init package

```
errors     << ov_init:make /home/manthan/workspace/catkin_ws_ov/logs/ov_init/build.make.004.log         
make[2]: *** No rule to make target '/usr/local/cuda-10.2/lib64/libcudart_static.a', needed by '/home/manthan/workspace/catkin_ws_ov/devel/.private/ov_init/lib/libov_init_lib.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:767: CMakeFiles/ov_init_lib.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

Is there any cuda dependency required for the package (I could not find in any of cmakelists)? Because my system does not have the 10.2 version installed shown in the error. 

Thank you

**Comment by goldbattle** [comment]
We don't depend at all on cuda. I am not sure why it would link, besides if you build OpenCV with it. Ceres I don't think have cuda support at all (which is the only difference between ov_core and ov_init deps).
