### ISSUE TITLE
Suddenly failing after good performance

### ISSUE THREAD

**Issue by raabuchanan** [rpng/open_vins#278]
Hello,
I'm running OpenVINS on a pretty easy log of a legged robot walking around a courtyard outside. OpenVINS works just fine until a specific moment where suddenly most of the visual features disappear and then the state diverges. I've added a picture of Rviz of just before the state diverges. 

My best guess is that most of the good features are very far away and maybe there is some parameter setting a maximum landmark distance from the camera? Any ideas? Thanks.

Right before divergence
![Screenshot from 2022-10-06 11-21-50](https://user-images.githubusercontent.com/5701905/194290143-b795d5f6-bfca-4fef-a327-2dae412cd2e3.png)

**Comment by goldbattle** [comment]
Do you have the bag? How many features are tracked during this, or is it due to the state diverging? Can you provide your calibration / launch / data?

**Comment by goldbattle** [comment]
Feel free to reopen if you have a specific bag to reproduce this, thanks!
