### ISSUE TITLE
anchor frame time problem

### ISSUE THREAD

**Issue by HeadReaper-hc** [rpng/open_vins#28]
You said set the first measurement to be the anchor frame,but in the FUNCTION single_triangulation`feat->anchor_clone_timestamp = feat->timestamps.at(feat->anchor_cam_id).back(); ` you set the newest time, Am I not understanding correctly?

besides  in the file of FeatureInitializerOptions.h`/// **Minimum** distance to accept triangulated features
        double max_dist = 40;
`

**Comment by goldbattle** [comment]
Yes, we do this since if we initialize a feature in the oldest frame, right away we need to perform an anchor change since that old clone will be marginalized. We do loop through and find which camera has the most measurements, and use that frame to anchor the feature in.

**Comment by HeadReaper-hc** [comment]
> Yes, we do this since if we initialize a feature in the oldest frame, right away we need to perform an anchor change since that old clone will be marginalized. We do loop through and find which camera has the most measurements, and use that frame to anchor the feature in.
thank you for your reply
