### ISSUE TITLE
Consulting VPQ plan of zupt

### ISSUE THREAD

**Issue by menglitanhua** [rpng/open_vins#281]
hello, could you please provide a formula derivation of VPQ zupt plan or some reference papers, corresponding code 280-297 in UpdaterZeroVelocity.cpp. I have a little doubt about the definition of R's residual  and the derivation of its jacobian, hoping to get your help. thanks.

**Comment by goldbattle** [comment]
Could you clarify your question? What does VPQ stand for? There is an open issue about the zero-velocity update here: https://github.com/rpng/open_vins/issues/273
