### ISSUE TITLE
Visual Thermal Inetial Dataset could be appled to this module?

### ISSUE THREAD

**Issue by MobilityAI** [rpng/open_vins#290]
Hi

I'm gonna implement visual thermal inertial esitmation with related dataset.
My plan is to modify config and launch file. Is it enough to implement? Or Is there something else i should  consider?
PLZ help me sir

**Comment by goldbattle** [comment]
Thermal cameras are very different from visual cameras. You would need to either change the tracking to use the full 10bit information, or scale the incoming thermal images to the 0-255 intensity based images that could then be used with traditional feature tracking methods.

**Comment by viciopoli01** [comment]
@MobilityAI please give a look at this for thermal cameras: https://github.com/jpl-x/x_multi_agent

**Comment by goldbattle** [comment]
> Online Photometric Calibration of Automatic Gain Thermal Infrared Cameras
> Manash Pratim Das, Larry Matthies, Shreyansh Daftry
https://arxiv.org/abs/2012.14292
https://github.com/mpdmanash/thermal_photometric_calibration
https://www.youtube.com/watch?v=364V3xBG1Tg
