### ISSUE TITLE
Any documentation on dynamic initialization?

### ISSUE THREAD

**Issue by copark86** [rpng/open_vins#294]
I am trying to improve the dynamic initialization so that it could work on some of the tough starting conditions that I have to deal with.

Do you have any good references or documentation on the algorithm used in the current dynamic initialization?

I was about to start the code reversing but it would be nice if there is a reference or documentation.

**Comment by goldbattle** [comment]
- https://docs.openvins.com/namespaceov__init.html
- https://pgeneva.com/downloads/reports/tr_init.pdf
- https://tdongsi.github.io/download/pubs/2011_VIO_Init_TR.pdf
- https://docs.openvins.com/classov__init_1_1DynamicInitializer.html

**Comment by copark86** [comment]
> * https://docs.openvins.com/namespaceov__init.html
> * https://pgeneva.com/downloads/reports/tr_init.pdf
> * https://tdongsi.github.io/download/pubs/2011_VIO_Init_TR.pdf
> * https://docs.openvins.com/classov__init_1_1DynamicInitializer.html

Awesome! Thank you.
