### ISSUE TITLE
DynamicInitializer : 538 line

### ISSUE THREAD

**Issue by jiaozhadexiaolang** [rpng/open_vins#296]
p_FinI0 = x_hat.block(size_feature * A_index_features.at(feat.first) + 6, 0, 3, 1);

**Comment by jiaozhadexiaolang** [comment]
A_index_features.at(feat.first) + 6

**Comment by jiaozhadexiaolang** [comment]
size_feature * A_index_features.at(feat.first) + 6
should 
A_index_features.at(feat.first)

why?  +6

**Comment by jiaozhadexiaolang** [comment]
v and g in the end of x_hat

**Comment by goldbattle** [comment]
The state should be the features, then velocity, then gravity
https://github.com/rpng/open_vins/blob/c3259430f0574c2911ff8e6ce888f6a1fcff5928/ov_init/src/dynamic/DynamicInitializer.cpp#L224-L231
https://github.com/rpng/open_vins/blob/c3259430f0574c2911ff8e6ce888f6a1fcff5928/ov_init/src/dynamic/DynamicInitializer.cpp#L368-L369

**Comment by qsisi** [comment]
Sorry to bother you again, but in my understanding, the x_hat is ordered as feat、vel、grav:

https://github.com/rpng/open_vins/blob/58afb2daf47498911100edc7452ccd7e42a2db50/ov_init/src/dynamic/DynamicInitializer.cpp#L477-L478

but when accessing the features:

https://github.com/rpng/open_vins/blob/58afb2daf47498911100edc7452ccd7e42a2db50/ov_init/src/dynamic/DynamicInitializer.cpp#L538

there is a "+6" at indexing, does it wrong?
