### ISSUE TITLE
question on feature representation

### ISSUE THREAD

**Issue by fratopa** [rpng/open_vins#299]
Hello, I am in the process of tuning the slam parameters to my setup and in the process I started to play around with the parameters `feat_rep_msckf` and `feat_rep_slam` which by default are set as
```
feat_rep_msckf: "GLOBAL_3D"
feat_rep_slam "ANCHORED_MSCKF_INVERSE_DEPTH"
```
I have been reading though your documentation and I have not found much about what these mean. In your website I found this page where I believe there is a complete list of possible parameters but it didn't really help much in their understanding. 

If someone knows more about them I'd appreciate if you could link me where they are discussed/explained.

**Comment by WoosikLee2510** [comment]
https://docs.openvins.com/update-feat.html#feat-rep
