### ISSUE TITLE
Why equalizeHist?

### ISSUE THREAD

**Issue by CvierXi** [rpng/open_vins#30]
https://github.com/rpng/open_vins/blob/7e10b8cc1dc971a862973e90429fe19d8fec6373/ov_core/src/track/TrackKLT.cpp#L36

Why to use equalizeHist? As we known, this may break down the brightness constancy assumption in Optical Flow Algorithm, and as a result, KLT may fail in some cases.

**Comment by goldbattle** [comment]
We found that it handled changes from going inside to outside better and
had better accuracy over not enabling it.
