### ISSUE TITLE
Monocular MSCKF launch example

### ISSUE THREAD

**Issue by ravindraji4** [rpng/open_vins#31]
Thank you very much for the open source software. 
Is it possible to upload and launch file for Monocular vision?
Or
How we can modify the existing launch file to make it function like Monocular camera?
Thank you very much in advance and for your suggestions.

**Comment by goldbattle** [comment]
You can change any of the launch files to have `max_cameras` equal to 1.
Let me know if you have any issues.

**Comment by ravindraji4** [comment]
Thanks!! it worked perfectly.
