### ISSUE TITLE
Redundant points for visualization

### ISSUE THREAD

**Issue by FengyuGuo** [rpng/open_vins#323]
https://github.com/rpng/open_vins/blob/74a63cf758f595cc280f2165e5a6576e7ef8521d/ov_msckf/src/ros/ROSVisualizerHelper.cpp#L49

should be 

`
modifier.resize(feats.size()); 
`

**Comment by goldbattle** [comment]
Does this actually have any effect on the visualization?

**Comment by FengyuGuo** [comment]
A little. 2/3 of the points are published with global coordinate of 0, 0, 0. So you will see points in the global reference point.

But if points are used for further usage like occupancy grid, this will have huge effect.
