### ISSUE TITLE
How to deal with the case where the diagonal elements of the covariance matrix are negative？

### ISSUE THREAD

**Issue by matrix246** [rpng/open_vins#324]
Hello, I made a small change to the code:

1: In StateHelper::EKFUpdate() function the matrix operation related to the covariance matrix, use the float data type instead of the double type.

Exception result:
1. The diagonal elements of the covariance matrix have negative values.

Questions:
1: Why the diagonal elements of covariance matrix have negative values?
2: Is there any way to avoid the situation where the diagonal elements in the covariance matrix is negative?
3: If the diagonal elements in the conference matrix have negative values, is there any better way to deal with it? The current solution is to exist the program directly.

Thanks a lot for your time.

**Comment by matrix246** [comment]
Thank you for your timely response.
We also noticed the following phenomena while trying:
1. When we use the latest version of OpenVINS with double precision, the case that the main diagonal is negative also occurs.
2. Another strange phenomenon is that with some data it is possible to use double OK, but the main diagonal is negative with float. For some data it is the other way around.
Have you ever been in a similar situation? What are the possible reasons for it?

Thank you for your time.

**Comment by goldbattle** [comment]
Do you have a dataset where this problem occurs? Likely this means your sensors are not properly calibrated, the noises are not correct, or the chi2 allowed an outlier / bad measurement to be in the update.

**Comment by HoEmpire** [comment]
You might also try to play around with the initial prior. Sometimes a bad initial prior can easily lead to negative diagonals.

**Comment by matrix246** [comment]
Thank you for your prompt reply. 
1、Such a problem occurred in our own collection of data sets
2、We will take a closer look at the sensor calibration procedure. 
3、Try adjusting the chi2 threshold.
Thanks again.
