### ISSUE TITLE
 question about the dummy.cpp

### ISSUE THREAD

**Issue by tadashi-hamada196** [rpng/open_vins#325]
I have a little question about the dummy.cpp, what does it use for?

**Comment by goldbattle** [comment]
This is used to provide the documentation pages for each namespace.
they don't contribute any code besides the comments above the namespace.

https://docs.openvins.com/namespaceov__core.html
https://github.com/rpng/open_vins/blob/master/ov_core/src/dummy.cpp#L22-L44
