### ISSUE TITLE
Tracking with open-vins failing on Android

### ISSUE THREAD

**Issue by Madhuparna04** [rpng/open_vins#326]
I have been trying to use open-vins on an Android phone (Samsung Galaxy S22 Ultra).
I used Kalibr to do the calibration (20 HZ Camera images from one back camera and 200 HZ IMU).
But tracking is failing with the values I got from Kalibr.

[Kalibr Camera report](https://drive.google.com/file/d/1O8AlVgHRX6z9wegRgnt9QnL2cv83EQju/view?usp=share_link)
[Kalibr Cam-imu report](https://drive.google.com/file/d/1PumJGcWBC5Rc5uESVMjs9tH7h5kjfwM9/view?usp=sharing) 

I used [allan-variance](https://github.com/ori-drs/allan_variance_ros) for finding the gyroscope and accelerometer noise and random walk.

I am using monocular currently and the returned pose seems to be increasing constantly. Number of features found is either 1 or 0. Also, the chi2 value I am observing is really high (30000 to 50000).

Any suggestion on how I can get the correct calibration results so that tracking works with open-vins?
Thank you!

**Comment by goldbattle** [comment]
Your transformation to the IMU to CAM in kalibr is over a meter.
I would get Kalibr to give a reasonable result before testing VIO.

**Comment by goldbattle** [comment]
![image](https://user-images.githubusercontent.com/2222562/231554298-41bc84a2-f418-4119-bff3-e61d3f343286.png)

**Comment by Madhuparna04** [comment]
I was able to get the right calibration values. Also for reference, [this](https://github.com/OSUPCVLab/mobile-ar-sensor-logger/wiki) has some default values for Android phones. Thank you!

**Comment by Genozen** [comment]
@Madhuparna04 , sorry to bother. I'm kind of interested in running OpenVins in Android platform. Any chance you could shed some light on how to get it onto Android?
