### ISSUE TITLE
about   scenes（ Green studio） to be used？

### ISSUE THREAD

**Issue by zhanghongyong123456** [rpng/open_vins#336]
Can this project be used for camera localization inside a green screen studio where most of the surroundings are green

**Comment by goldbattle** [comment]
There needs to be sufficient environmental texture to perform feature tracking. Additionally this is an odometry method, thus will slowly drift over time unless you leverage Aruco Tags. Hope this helps.

**Comment by zhanghongyong123456** [comment]
> Aruco Tags

Thank you for your reply. Since I am new to this direction, is there any good recommended project for my usage scenario? like our project openvins or orb-slam project

**Comment by goldbattle** [comment]
Most systems extract environmental features, so they will all suffer from an all green environment.
You could checkout these projects from a quick google search:
- https://github.com/berndpfrommer/tagslam_root
- https://github.com/ProjectArtemis/aprilslam

**Comment by zhanghongyong123456** [comment]
> Most systems extract environmental features, so they will all suffer from an all green environment. You could checkout these projects from a quick google search:
> 
> * https://github.com/berndpfrommer/tagslam_root
> * https://github.com/ProjectArtemis/aprilslam

ok，i learn it ,thank you very much
