### ISSUE TITLE
Initialisation not occuring once I changed camera parameters

### ISSUE THREAD

**Issue by meepo20** [rpng/open_vins#348]
My camera is translated by 0.2 in the X direction
```
<frame_name>front_cam_link</frame_name>
<hack_baseline>0.07</hack_baseline>
</plugin>
<pose>0.2 0 0 0 -0 0</pose>`
```

I've changed the resolution and camera parameters
```
cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [0, 0, 0, 0.2]
    - [0, 0, 0, 0]
    - [0, 0, 0, 0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0,0,0,0]
  distortion_model: radtan
  intrinsics: [0,0,0,0] #fu, fv, cu, cv
  resolution: [1920, 1080]
```

However on launch the output is this
[run_subscribe_msckf-1] Setting printing level to: INFO
[run_subscribe_msckf-1] overriding node max_cameras with value from ROS!
[run_subscribe_msckf-1] overriding node max_cameras with value from ROS!
[run_subscribe_msckf-1] overriding node use_stereo with value from ROS!
[run_subscribe_msckf-1] overriding node use_stereo with value from ROS!
[run_subscribe_msckf-1] subscribing to IMU: /nick/imu/out
[run_subscribe_msckf-1] subscribing to cam (mono): /nick/front/image_raw
[run_subscribe_msckf-1] [TIME]: 0.0249 seconds total (40.1 hz, 11.30 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0702 seconds total (14.2 hz, 41.90 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0236 seconds total (42.4 hz, 44.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0453 seconds total (22.1 hz, 46.90 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0320 seconds total (31.2 hz, 51.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0493 seconds total (20.3 hz, 46.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0224 seconds total (44.5 hz, 41.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0400 seconds total (25.0 hz, 43.30 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0161 seconds total (62.0 hz, 42.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0434 seconds total (23.0 hz, 38.90 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0151 seconds total (66.4 hz, 37.90 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0338 seconds total (29.6 hz, 40.90 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0175 seconds total (57.2 hz, 41.90 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0380 seconds total (26.3 hz, 36.90 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0195 seconds total (51.2 hz, 41.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0571 seconds total (17.5 hz, 44.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0174 seconds total (57.6 hz, 39.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0328 seconds total (30.5 hz, 34.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0173 seconds total (57.7 hz, 29.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0398 seconds total (25.1 hz, 34.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0173 seconds total (57.7 hz, 34.20 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0408 seconds total (24.5 hz, 30.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0274 seconds total (36.4 hz, 29.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0399 seconds total (25.1 hz, 25.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0185 seconds total (54.1 hz, 24.60 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0347 seconds total (28.8 hz, 25.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0157 seconds total (63.6 hz, 28.70 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0343 seconds total (29.2 hz, 33.30 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0278 seconds total (35.9 hz, 41.80 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0332 seconds total (30.1 hz, 36.80 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0141 seconds total (70.8 hz, 31.80 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0329 seconds total (30.4 hz, 26.80 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0185 seconds total (54.0 hz, 21.60 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0406 seconds total (24.6 hz, 24.80 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0162 seconds total (61.8 hz, 23.70 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0326 seconds total (30.7 hz, 25.30 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0318 seconds total (31.4 hz, 48.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0373 seconds total (26.8 hz, 43.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0167 seconds total (59.7 hz, 38.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0416 seconds total (24.1 hz, 33.30 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0120 seconds total (83.1 hz, 28.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0414 seconds total (24.2 hz, 35.00 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0136 seconds total (73.3 hz, 33.00 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0356 seconds total (28.1 hz, 49.00 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0181 seconds total (55.1 hz, 50.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0380 seconds total (26.3 hz, 55.40 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0252 seconds total (39.6 hz, 49.60 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0563 seconds total (17.8 hz, 45.60 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0175 seconds total (57.1 hz, 45.60 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0376 seconds total (26.6 hz, 42.60 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0194 seconds total (51.7 hz, 40.10 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0420 seconds total (23.8 hz, 37.60 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0403 seconds total (24.8 hz, 33.00 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0410 seconds total (24.4 hz, 33.70 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0234 seconds total (42.7 hz, 31.20 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0365 seconds total (27.4 hz, 26.30 ms behind)
[run_subscribe_msckf-1] [TIME]: 0.0244 seconds total (40.9 hz, 26.30 ms behind)

**Comment by goldbattle** [comment]
Your focal and camera center can't be zero. I would check this calibration
and go from there.

**Comment by meepo20** [comment]
Thanks will give it a try
