### ISSUE TITLE
Unable to perform state estimation for d455

### ISSUE THREAD

**Issue by Aishkrish18** [rpng/open_vins#351]
Hey @goldbattle , thanks for your reply in one of the issues. I am creating a new issue here now for the same problem . I have a short question. I am running d455 using Open vins in ros1 noetic and after this output shown below I don't see any tracking at all. I am not quite sure where I went wrong. I disabled stereo mode everywhere and changed to mono with 1 camera. I am trying to run the estimation live with my d455 camera .
You mentioned that it might be a problem with verbosity. Could you elaborate a bit about that here? I checked the topics from the camera that are published and they seem to be publishing fine at the rate mentioned in the steps.  Thank you so much for your help!
![Screenshot from 2023-06-23 12-29-19](https://github.com/rpng/open_vins/assets/47241581/c5e99bfc-c5b8-4511-8551-6f05aade429f)

**Comment by goldbattle** [comment]
Can try adding `verbosity:=DEBUG` to see what is happening.
https://github.com/rpng/open_vins/blob/master/ov_msckf/launch/simulation.launch#L8C16-L8C25


Ensure you are using the latest code from the master branch.

**Comment by goldbattle** [comment]
Feel free to reopen if you were unable to figure it out (with a bag too).
