### ISSUE TITLE
Facing error while running on mono

### ISSUE THREAD

**Issue by EhrazImam** [rpng/open_vins#354]
roslaunch ov_msckf subscribe.launch 
... logging to /home/enord/.ros/log/aac2593a-15e0-11ee-9dea-b48c9d350213/roslaunch-enord-5311.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://enord:32925/

SUMMARY
========

CLEAR PARAMETERS
 * /ov_msckf/

PARAMETERS
 * /ov_msckf/config_path: /home/enord/catki...
 * /ov_msckf/max_cameras: 1
 * /ov_msckf/record_timing_filepath: /tmp/traj_timing.txt
 * /ov_msckf/record_timing_information: False
 * /ov_msckf/use_stereo: True
 * /ov_msckf/verbosity: INFO
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    ov_msckf (ov_msckf/run_subscribe_msckf)
    rvizvisualisation (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[ov_msckf-1]: started with pid [5337]
process[rvizvisualisation-2]: started with pid [5338]
overriding node verbosity with value from ROS!
Setting printing level to: INFO
overriding node max_cameras with value from ROS!
overriding node max_cameras with value from ROS!
overriding node use_stereo with value from ROS!
overriding node record_timing_information with value from ROS!
overriding node record_timing_filepath with value from ROS!
overriding node max_cameras with value from ROS!
overriding node use_stereo with value from ROS!
subscribing to IMU: /mavros/imu/data
subscribing to cam (mono): /front_camera
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.4) /tmp/build_opencv/opencv/modules/core/src/matrix.cpp:250: error: (-215:Assertion failed) s >= 0 in function 'setSize'

================================================================================REQUIRED process [ov_msckf-1] has died!
process has died [pid 5337, exit code -6, cmd /home/enord/catkin_ws/devel/lib/ov_msckf/run_subscribe_msckf __name:=ov_msckf __log:=/home/enord/.ros/log/aac2593a-15e0-11ee-9dea-b48c9d350213/ov_msckf-1.log].
log file: /home/enord/.ros/log/aac2593a-15e0-11ee-9dea-b48c9d350213/ov_msckf-1*.log
Initiating shutdown!
================================================================================
[rvizvisualisation-2] killing on exit
[ERROR] [1687976762.326141414]: [registerSubscriber] Failed to contact master at [localhost:11311].  Retrying...
[ov_msckf-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by Jominsu99** [comment]
how did you solve this problem?
