### ISSUE TITLE
Simple Tutorial RViz launch missing `-d` path to `.rviz` file

### ISSUE THREAD

**Issue by cod3monk3y** [rpng/open_vins#357]
Under the [ROS 1 section for the Simple Tutorial](https://docs.openvins.com/gs-tutorial.html#gs-tutorial-ros1), the launch command reads

```
rviz # term 2
```

Executing that directly will show `Fixed Frame [map] does not exist` because RViz is using `default.rviz` configuration. I had to specify the `.rviz` file using `-d` to get the visualization working:

```
$ cd ~/openvs_ws
$ rviz -d src/open_vins/ov_msckf/launch/display.rviz
```

After this it works great!

Is this just my setup, or should the doc change from just `rviz` to something like: `rviz -d src/open_vins/ov_msckf/launch/display.rviz`?

**Comment by cod3monk3y** [comment]
I assume yes, since you do this [in the demo video](https://youtu.be/rBT5O5TEOV4?t=2351).

**Comment by goldbattle** [comment]
There is a comment above that about what config to open
> For RVIZ, one can open the ov_msckf/launch/display.rviz configuration file.

But directly from command line might help those newer to the project
