### ISSUE TITLE
Should IMU config `Tw` and `R_IMUtoGYRO` both be set to Kalibr `imu0:gyroscope:M`?

### ISSUE THREAD

**Issue by cod3monk3y** [rpng/open_vins#358]
Just clarifying comments from `kalibr_imu_chain.yaml` in `config/*/kalibr_imu_chain.yaml`. I checked (almost) all of the configs and they all have the same comment (minor indentation added for clarity):

```yaml
  # how to get from Kalibr imu.yaml result file:
  #   - Tw is           imu0:gyroscopes:M:
  #   - R_IMUtoGYRO: is imu0:gyroscopes:M:
  #   - Ta is           imu0:accelerometers:M:
  #   - R_IMUtoACC      not used by Kalibr
  #   - Tg is           imu0:gyroscopes:A:
```

Is it correct that `Tw` and `R_IMUtoGYRO` should both be `imu0:gyroscopes:M:`? If so, this leaves `imu0:gyroscopes:C_gyro_i` from Kalibr unused.

**Comment by goldbattle** [comment]
No it would be `C_gyro_i`, good catch.
