### ISSUE TITLE
Question about ZUPT derivation

### ISSUE THREAD

**Issue by tianlong312** [rpng/open_vins#360]
![屏幕截图 2023-07-19 140833](https://github.com/rpng/open_vins/assets/52013331/9d39ae86-27fd-47c2-9e3b-07f4858eb4ba)

Hi there, I am reading the docs about ZUPT derivation from OpenVINS website and I have a question about the derivative (dz)/(db), should the sign be positive instead of negative in the derivation since z is actually -w_m+b_g+n_g?

**Comment by goldbattle** [comment]
We take the derivative of the following function:
![image](https://github.com/rpng/open_vins/assets/2222562/495c8500-9cd3-4145-8e72-216402c69d9d)

Which gives you the negative for all three Jacobians. There is then a discussion the page about how we compute the residual as the "true" measurement is actually us saying that we should have zero acceleration and zero angular velocity. You can see the implementation here:
https://github.com/rpng/open_vins/blob/e274c656324f84b9f2730eacd0cf54a6f8b74bb8/ov_msckf/src/update/UpdaterZeroVelocity.cpp#L160-L178

**Comment by tianlong312** [comment]
Thanks for your reply, does that mean the notation from the OpenVINS website is wrong? Instead of taking derivative of the residual as in the documentation, we are taking derivative of the “true ”measurement.

**Comment by goldbattle** [comment]
For EKF / filter system we always formulate the function $$z_m = h(x) + n$$ where we then find the derivative in respect to. There is some subtilty with having the error state for orientation. This function is then re-arranged to give $$\tilde{z} = z_m - h(\hat{x}) = \mathbf{H} \tilde{x} + n$$
Hope this helps.

**Comment by bereze** [comment]
If the derivative of the following function is taken:

<img width="263" height="74" alt="Image" src="https://github.com/user-attachments/assets/46c4f95a-b596-43d1-88ef-c1f2c5b7838f" />

then following the left jacobian of SO(3): $\mathbf J_{\mathrm{left}} = -[\mathbf R\mathbf p]_\times$ , the jacobian wrt. `R` should be 
$[ R g]\times$ ​, but the implementation is ` H.block(6 * i + 3, 0, 3, 3) = -w_accel * skew_x(R_GtoI_jacob * _gravity); `. Is that wrong or do I miss something?
