### ISSUE TITLE
Is it planned to add RGB-D mode for D455/435/457 cameras?

### ISSUE THREAD

**Issue by Userpc1010** [rpng/open_vins#363]
The rgb-d mode performs well indoors and at dusk, thanks to the laser projector, it also works quite accurately, maybe using a ready-made depth if it is available in mono mode could somehow improve camera initialization or increase accuracy? Perhaps it will also be useful for sharp jumps and turns when moving the camera?

**Comment by goldbattle** [comment]
We don't support RBG-D sensors. You could add this support yourself if you desire for this. It would come with challenges including modeling the noise, sensor asynchronicity and calibration. I am not sure of the depth quality of the intel realsense sensors.
