### ISSUE TITLE
ROS2 Docker always throws opencv2 error and does not build

### ISSUE THREAD

**Issue by Aishkrish18** [rpng/open_vins#364]
![Screenshot from 2023-07-27 15-34-12](https://github.com/rpng/open_vins/assets/47241581/007e26ce-fa41-4f02-a6c1-17a86d997653)

Hey, 
I am still facing the same error as mentioned above. Although, on trying to build opencv from source, it still gives the same error. This is the same case for both ROS2 dockers since I tried both of them.  Could you suggest a solution for this if it has already worked out for any of you? Would be very much useful to have a ROS2 docker, since ros1 dockers works perfectly fine for me.

Also is it possible to run or use a docker file for foxy? 

Regards,
AIshwarya

_Originally posted by @Aishkrish18 in https://github.com/rpng/open_vins/issues/346#issuecomment-1653646095_

**Comment by goldbattle** [comment]
Please provide the OS, OpenCV, ROS version that you are trying with. If you can reproduce in one of the dockers that would be helpful too.
