### ISSUE TITLE
State estimation completely goes out of the rviz grid on performing with ZED2

### ISSUE THREAD

**Issue by Aishkrish18** [rpng/open_vins#366]
Hey,
First of all thank you so much for this great open source work and for your instant replies for clearing our doubts. 
I am performing state estimation for ZED2 camera and I am currently facing this problem where the tracking goes off the rviz grid and it shoots off. I perfomed correct calibration and i have pasted them here. I am not sure if there are certain specific parameters that i have to tune for having them exactly follw the path of the camera. 

I have herewith attavched the calibration files and the screenshot of how it shoots off from the grid. 
![Screenshot from 2023-07-28 15-52-50](https://github.com/rpng/open_vins/assets/47241581/cbf80a32-3fbc-4a08-a2d9-4ac9d2b64055)
![Screenshot from 2023-07-31 10-11-40](https://github.com/rpng/open_vins/assets/47241581/a8c62c76-7762-42d6-8308-1b9fb537892c)
![Screenshot from 2023-07-31 10-12-16](https://github.com/rpng/open_vins/assets/47241581/53cc73e8-8589-47ca-83fe-c42e3c29c270)
![acceleration](https://github.com/rpng/open_vins/assets/47241581/bcf114ff-5b18-43ce-bfa7-b1c1ddbe0588)
[zed2_cam_imu_calib4-results-imucam.txt](https://github.com/rpng/open_vins/files/12212942/zed2_cam_imu_calib4-results-imucam.txt)

**Comment by Aishkrish18** [comment]
Update: This action was somewhat similar for d435 as well. It would be great if someone can assist me on how to fix it, so that i can compare the results and make a conclusion.  i plan to use this algorithm for my master thesis to work and tune more on top of the existing algorithm :)

**Comment by Aishkrish18** [comment]
By imu intrinsics you mean the allan variance ros -imu  bias values or imu-camera calibration?  Or am i missing something other than that?

**Comment by goldbattle** [comment]
Kalibr IMU-camera calibration, should be the --imu-models parameter to
scale-missalignment I believe?
Allan variance will get your noise parameters, not the intrinsics.

**Comment by Aishkrish18** [comment]
Not sure if i understood you correctly,  but you mean I should calibrate imu camera using the model parameter scale-misalignment instead of "calibrated" is it? for ZED2 and d435? This will help solving the issue?

**Comment by Aishkrish18** [comment]
![Screenshot from 2023-08-02 15-55-29](https://github.com/rpng/open_vins/assets/47241581/658ae20d-161d-4945-82b4-6270196716f4)
![Screenshot from 2023-08-02 15-53-33](https://github.com/rpng/open_vins/assets/47241581/f68db630-dc72-4bbb-8b7d-1de59f56ebfb)


On performing calibration once again by using scale-misalignment, i was able to retrieve the intrinsics of IMU. But this is still not helping and it still continues to shoot out of the grid. I have herewith attached the values  and the cam chain files 
[zed2_cam_imu_calib4-results-imucam.txt](https://github.com/rpng/open_vins/files/12240838/zed2_cam_imu_calib4-results-imucam.txt)
[zed2_cam_imu_calib4-report-imucam.pdf](https://github.com/rpng/open_vins/files/12240839/zed2_cam_imu_calib4-report-imucam.pdf)

**Comment by yangyulin** [comment]
Have you fully excited the motion when doing calculations?It is clear that the IMU is not good, The scale correction for gyro and accel is too largeSent from my iPhoneOn Aug 2, 2023, at 7:00 AM, Tetrix ***@***.***> wrote:﻿


On performing calibration once again by using scale-misalignment, i was able to retrieve the intrinsics of IMU. But this is still not helping and it still continues to shoot out of the grid. I have herewith attached the values  and the cam chain files
zed2_cam_imu_calib4-results-imucam.txt
zed2_cam_imu_calib4-report-imucam.pdf

**Comment by goldbattle** [comment]
There are also some discussions about using ZED / ZED2 if you search the issues:
- https://github.com/rpng/open_vins/issues/52
- https://github.com/rpng/open_vins/issues/133
- https://github.com/rpng/open_vins/issues/157

**Comment by goldbattle** [comment]
Also feel free to pose your ZED2 configs if you are able as it seems quite a few people have tried to use this device. Many thanks!
