### ISSUE TITLE
Doesn't work on processed rosbags

### ISSUE THREAD

**Issue by Jominsu99** [rpng/open_vins#370]
Hello i need help.
The raw rosbag file works fine for both serial.launch and subscribe.launch. However, when using processed rosbag topics, the following error occurs.
I brought an example, but as a result of converting the compressed image into a raw image and executing serial.launch, it does not work with the following error message.

![processbagerror](https://github.com/rpng/open_vins/assets/82068871/4472f920-0de5-4542-b968-458f4d7e50f9)

What could be the problem?

processed bag topic compressed -> raw
t.bag is part of handheld.bag.

![baginfo](https://github.com/rpng/open_vins/assets/82068871/31328bee-a713-4ac4-a7b4-157d6fe36556)

estimator_config.yaml
kalibr_imucam_chain.yaml

![imuchain](https://github.com/rpng/open_vins/assets/82068871/0c69a563-b361-48f1-bce9-29ade39657d3)

kalibr_imu_chain.yaml

![imucam](https://github.com/rpng/open_vins/assets/82068871/e5a8e47b-84db-4505-85b6-4d3f5e99041c)

**Comment by Jominsu99** [comment]
Apart from the problem above, the same error as above occurred when serial.launch was executed with a data set that did not have an error with subscribe.launch.

![class_loader error](https://github.com/rpng/open_vins/assets/82068871/de19e92c-9a56-4286-a7cd-32cbf681755a)

I don't know how to fix it. I need help

**Comment by goldbattle** [comment]
It looks like the dataset has finished being processed correctly. In your first screenshot where no information is posted likely means the topic names are incorrectly configured or the timestamps of the converged images are no longer correct. I recommend investigating this and inspecting with `rqt_bag` utility.
