### ISSUE TITLE
cv::aruco::CornerRefineMethod::CORNER_REFINE_SUBPIX; // people with newer opencv might fail here

### ISSUE THREAD

**Issue by maximpavliv** [rpng/open_vins#38]
I get an error when building, at lines 48 and 59 of ov_core/src/track/TrackAruco.h . I have OpenCV 3.2. Which version of OpenCV are you using?

**Comment by goldbattle** [comment]
We recommend building with OpenCV 3.4.6:
https://docs.openvins.com/gs-installing.html#gs-install-opencv
