### ISSUE TITLE
Why add cache_t_off in fast_state_propagate?

### ISSUE THREAD

**Issue by WZG3661** [rpng/open_vins#380]
On the line 154 of Propagator.cpp, the timestamp is originally in IMU clock, why add cache_t_off?
```C++
  double time0 = cache_state_time + cache_t_off;
  double time1 = timestamp + cache_t_off;
```

**Comment by goldbattle** [comment]
The timestamp of the state is actually the camera time (see the bottom of the `propagate_and_clone()` function). Thus we need to take into account the time offset the first time the fast propagate function is called. After the first time the fast propagation is called, the `cache_state_time` will be in the IMU clock frame, so the `cache_t_off` will be zero (see bottom of `fast_state_propagate()` function).
