### ISSUE TITLE
How to run openvins in gazebo?

### ISSUE THREAD

**Issue by ababayi** [rpng/open_vins#381]
hello how can I run this awesome algorithm in gazebo and ros?
is there any prebuild launch file? or instruction?

should I remap any topics?

**Comment by goldbattle** [comment]
This isn't something we currently support or have documentation about. If you are able to simulate two cameras and an IMU and get their calibration then there should be no issue running OpenVINS on it. Feel free to post how to do it if you are able to generate the data.

**Comment by goldbattle** [comment]
There are some older issues about this, feel free to take a look at them: https://github.com/rpng/open_vins/issues?q=gazebo
