### ISSUE TITLE
may i know  how to close imu? 

### ISSUE THREAD

**Issue by huang-shijie** [rpng/open_vins#383]
i want to just use stereo , but i can't find the parameter which can close the imu.

**Comment by goldbattle** [comment]
Hi, could you clarify your question?

**Comment by huang-shijie** [comment]
hi,my question is  i  want to just use stereo  to run openvins, not  use  stereo + imu.

**Comment by goldbattle** [comment]
This is a visual-inertial system. It is not able, nor will it ever be able to run without the IMU. Hope this helps.
