### ISSUE TITLE
build failed on WSL Ubuntu 20.04 ROS 1 neotic 

### ISSUE THREAD

**Issue by kruzel** [rpng/open_vins#384]
CMakeFiles/ov_msckf_lib.dir/src/update/UpdaterMSCKF.cpp.o] Error 1

[build.make.000.log](https://github.com/rpng/open_vins/files/12670897/build.make.000.log)

![image](https://github.com/rpng/open_vins/assets/975963/fde54277-8fb3-4ec4-b7fd-4749968ffd3e)

**Comment by goldbattle** [comment]
This is likely an out of memory error.
Not much I can do besides recommending adding a swapfile or building with
catkin build -j1
https://gist.github.com/susanBuck/b9310f8f0886105008a2f6a18a18d7ae

Shouldn't be an issue with WSL, but I have never tried this...

**Comment by kruzel** [comment]
my VM has 32GB RAM,
should I increase?
Ofer Kruzel
M: +972 (54) 4516627

**Comment by kruzel** [comment]
works on non VM matchine
