### ISSUE TITLE
Test webcam example

### ISSUE THREAD

**Issue by Userpc1010** [rpng/open_vins#387]
How can I bypass the limitation and use only OpenCV: 4.7.0?

![Screenshot from 2023-10-05 23-31-47](https://github.com/rpng/open_vins/assets/54418413/087be79f-2c2b-49bb-914f-acfba998281c)

**Comment by goldbattle** [comment]
Maybe you have not specified the correct camera. Do you have the camera ID
set correctly?
Are you able to compile the OpenCV explain, or run the other binaries from
OpenVINS?

**Comment by Userpc1010** [comment]
Yes, apparently the problem was in the camera, at the moment I building openvins with librealsense directly (without ROS) and do not observe this problem.

![Screenshot from 2023-10-07 21-28-16](https://github.com/rpng/open_vins/assets/54418413/baeb5d5c-2615-4da7-bf2a-6757a3b9296f)
