### ISSUE TITLE
Static initialization failed

### ISSUE THREAD

**Issue by huang-shijie** [rpng/open_vins#390]
When running the source code, it prompts that static initialization is always unsuccessful, and the terminal displays as follows:
![10082](https://github.com/rpng/open_vins/assets/87986703/8e6796e8-d301-445b-957d-31ceaf5abaf6)
![1008](https://github.com/rpng/open_vins/assets/87986703/f8806502-740e-4871-89b6-e70402988cc9)
how to solve it.

**Comment by Aishkrish18** [comment]
In order to do static initialisation, the camera must be activated in all directions and orientations by giving enough initial movements. Maybe you are not activating all orientations enough?

**Comment by huang-shijie** [comment]
thanks for you answer,i have solved this issue.
![Screenshot_2023-10-10-07-59-24-77_e39d2c7de19156b0683cd93e8735f348](https://github.com/rpng/open_vins/assets/87986703/64879412-69f5-443a-831f-407b1662239e)

**Comment by goldbattle** [comment]
@Alex-Beh you should just need to pick it up from static.
