### ISSUE TITLE
Do the Tw, R_IMUtoGYRO, Ta, and Tg matrices in the kalibr_imu_chain.yaml file need to be calibrated? what their function is？

### ISSUE THREAD

**Issue by huang-shijie** [rpng/open_vins#393]
This video I refer to is [https://www.youtube.com/watch?v=rBT5O5TEOV4&t=2721s&ab_channel=PatrickGeneva](url).
He calibrated these matrices, but I did not calibrate them, and the algorithm can still run. I would like to ask whether these matrices will have a great impact on the algorithm effect or the stability of the operation.

**Comment by goldbattle** [comment]
They should have an impact if the IMU used does not have good factory calibration (e.g. these matrices are non-identity).
