### ISSUE TITLE
How to reset the openvins system

### ISSUE THREAD

**Issue by TankRedHot** [rpng/open_vins#398]
I wanna to reset the system when the track is lost. But i failed sometimes.
There are some description in the VioManager.cpp:
  // If we do not have VIO initialization, then try to initialize
  // TODO: Or if we are trying to reset the system, then do that here!

Does anyone have a reference implementation, please

**Comment by goldbattle** [comment]
You might be better off just re-spawning the whole ROS node, or doing it in the top level main file.
