### ISSUE TITLE
ov_init built failed

### ISSUE THREAD

**Issue by zpf103** [rpng/open_vins#406]
hi: 
I try to build OpenVins on unbuntu20 on ROS1, but building is failed when building ov_init with strange errors like this
![2023-12-11 17-06-18 的屏幕截图](https://github.com/rpng/open_vins/assets/46625620/e4835fb8-757c-4f3d-97d4-580cb3017bca)
![2023-12-11 17-06-22 的屏幕截图](https://github.com/rpng/open_vins/assets/46625620/b035e671-3a0a-4104-9c9c-189615d01455)

**Comment by Mikhail2017** [comment]
Or maybe the version is outdated. A default version in Ubuntu 20 is 1.14.0-4.
Anyway I've built custom ceres from sources and got rid of these compilation errors.
You can take 399cda773035d99eaf1f4a129a666b3c4df9d1b1 e.g.
