### ISSUE TITLE
OpenVINS requires infrared stereo or RGB colour camera for D435I setup ?

### ISSUE THREAD

**Issue by shyam-botsync** [rpng/open_vins#407]
I am sort of confused which data to use with D435i. The infra red images has bright dots [typical of infrared stereo camera], I am suspecting it won't work with kalibr routines.

**Comment by gianlucaparadiso** [comment]
Hi, you can use the infrared image topics with Kalibr and openVINS. To avoid any possible issue with the "dots" you can disable the infrared emitter in the realsense launch file (or just cover up the emitter with some tape). With the emitter turned off it works well for me.

You can also take a look at this issue #64 for more info on using the D435i with openVINS.
