### ISSUE TITLE
Does OpenVINS currently use SEVIS?

### ISSUE THREAD

**Issue by apache8080** [rpng/open_vins#41]
As the title says, I was wondering if the current version of OpenVINS uses the SEVIS algorithm mentioned in this paper: [https://arxiv.org/pdf/1903.08636.pdf](https://arxiv.org/pdf/1903.08636.pdf)

**Comment by goldbattle** [comment]
OpenVINS is just an odometry-based visual-inertial system, as compared to SEVIS which looked to build a map. This is not in the OpenVINS codebase, and while we are planning on open sourcing down the line, there is no timeline on that release. I recommend taking a look at the OpenVINS paper which outlines exactly what is implemented:
http://udel.edu/~pgeneva/downloads/papers/c10.pdf
