### ISSUE TITLE
Issues related to running the neighborhood_01 dataset

### ISSUE THREAD

**Issue by doublesorrymaker** [rpng/open_vins#416]
Hello, when using this data set configuration without modification, the trajectory is as follows:
![open_vins整体轨迹](https://github.com/rpng/open_vins/assets/75357982/f7a547b1-4c1c-42de-8fbc-2a9ab673064f)
The visual accuracy is not very good. What is the reason for the above situation? I set alib_cam_extrinsics, calib_cam_timeoffset to true, and modified the relevant settings of zupt. The situation has improved, but the following problems have arisen:
![open_vins局部1](https://github.com/rpng/open_vins/assets/75357982/d0e0e524-423e-434d-804e-3742fdefb200)

![open_vins局部2](https://github.com/rpng/open_vins/assets/75357982/8e5c15d8-8f9b-46cc-a9d0-6db09cd83751)
The trajectory of these intersections that require slowing down and turning has drifted, which seems to be caused by the car decelerating and affecting the imu data. What ideas can be improved?
At the same time, I also observed that the drift of the z-axis is also very serious. Even if I set calib_imu_g_sensitivity to true, there is still no improvement. The situation is as follows:
![open_vins局部3](https://github.com/rpng/open_vins/assets/75357982/5c59a5e8-8746-4486-9812-28f29cf92547)

**Comment by goldbattle** [comment]
I believe this is something I saw. The z-axis I attribute to poor IMU calibration (or gravity magnitude), but I am not sure. Typically the estimation of velocity along the direction of travel (forward backwards) is the worst. This can be seen by the large amount of corrections during the stops and turns. You can try to increase the window size to have a longer window and maybe better velocity.

if you are interested in the problems of VIO and constant velocity you might be interested in these works:
- https://mars.cs.umn.edu/papers/KejianWu_VINSonWheels.pdf
- https://pgeneva.com/downloads/preprints/Yang2019RAL.pdf
- https://pgeneva.com/downloads/papers/Lee2020IROS.pdf


In general we care about the percent trajectory drift as a function of distance. Typically we want a 1% drift rate for good sensors. Here it looks like ~70m drift for a 2.3km trajectory so around ~3% trajectory drift. This could be better (I would recalibrate it if I still had the sensor and try again), but I don't think is too too unreasonable for odometry.
