### ISSUE TITLE
Using Line Features

### ISSUE THREAD

**Issue by hesheit** [rpng/open_vins#419]
First of all, thanks a lot for the great work !!

I read the paper "Visual-Inertial Odometry with Point and Line Features" and not sure how to incorporate line features in OpenVINS.

Is there any repository that implements the algorithm in the paper ?
Could you please guide me on this ?

Thanks again

**Comment by goldbattle** [comment]
This isn't something open sourced. A good starting point is to get the feature tracking working and visualizing then go onto the 3d triangulation and estimation which is detailed in the paper. Hope this helps.
