### ISSUE TITLE
Cannot build the content

### ISSUE THREAD

**Issue by Jawaheru** [rpng/open_vins#431]
![312467150-60484430-7cb3-4f59-9e5d-3ead739d82fe](https://github.com/rpng/open_vins/assets/2222562/6aeddd4a-7c52-4b51-b1bd-8dd2dbc68a75)

**Comment by goldbattle** [comment]
Hi, I saw you edited your post. Were you able to solve the original problem? It looks like it is because you killed the building. If you are running into memory issues you can build with `catkin build -j1` to limit the number of parallel builds.

**Comment by goldbattle** [comment]
I now see you opened a second issue https://github.com/rpng/open_vins/issues/432. Closing this one

**Comment by Jawaheru** [comment]
I killed the build after it took me forever waiting to complete, however I tried the command previously and its not working. I will get back to building this and update it if any further solution worked. Ty > I now see you opened a second issue https://github.com/rpng/open_vins/issues/432. Closing this one
