### ISSUE TITLE
Cannot build openvins aruco

### ISSUE THREAD

**Issue by Jawaheru** [rpng/open_vins#432]
Catkin build shows this failure, I i use melodic and ubuntu 18.04
![image](https://github.com/rpng/open_vins/assets/100447343/dfcd6c69-f380-440a-beb9-3e23d4e17ee5)
I tried to change the trackArcu.coo to opencv3 and 4
Still same error

**Comment by goldbattle** [comment]
Hi, it looks like you do not have aruco opencv contrib module built. What version of opencv are you using? If you are not interested in using the aruco tag SLAM feature functionallity then you can disable with any of the following:
```
catkin config --cmake-args -DENABLE_ARUCO_TAGS=OFF
catkin build --cmake-args -DENABLE_ARUCO_TAGS=OFF
```
