### ISSUE TITLE
how to use my .bag data set for mono camera 

### ISSUE THREAD

**Issue by hessaHamad** [rpng/open_vins#439]
Hi,

am trying to use my own dataset in . bag file, contains IMU and raw images of mono cam. I followed patrick's youtube video and all my config files are set as shown there, 
The steps I tried:
#Term 0
roscore
#Term 1
rviz -d src/open_vins/ov_msckf/launch/display.rviz
#Term 2
rosbag play mydataset.bag
#Term 3
(no error but keep waiting for the data, it might be a topic issue)
roslaunch ov_msckf subscribe.launch config:=gp dolivetraj:=true max_cameras:=1 dataset:=Test03_newcalib

and 
(error as shown)
roslaunch ov_msckf subscribe.launch config_path:=/home/gp/workspace/catkin_ws_ov/src/open_vins/config/gp/estimator_config.yaml dataset:=Test03_newcalib bag:=Test03_newcalib.bag

![Screenshot from 2024-04-29 14-59-22](https://github.com/rpng/open_vins/assets/122529202/5c88090f-f47b-41e9-9534-613afd2d7dce)
![Screenshot from 2024-04-29 15-04-36](https://github.com/rpng/open_vins/assets/122529202/ca1526dc-73ad-475f-ab10-89eb21cb095e)

**Comment by VivekMangeUD** [comment]
Hey

I see that you are using the dataset parameter in the launch file, To use that feature you need to set the below param as true.
    <arg name="dobag"       default="false" />  

Also, The end of the launch file seems correct, Openvins is waiting for the rostopics imu and video_source/raw. Can you verify they are being published by the bag file. Can you share the snippet of the Rviz window as well.

**Comment by goldbattle** [comment]
I recommend making sure your topics are correct. You can use rostopic to inspect the connections. `video_source/raw` looks to be missing a `/` at the start? Please reopen with further details on the topics your driver is producing `rostopic list`
