### ISSUE TITLE
sequential measurement update to reduce process load

### ISSUE THREAD

**Issue by amosleeday** [rpng/open_vins#44]
In measurement update, QR decomposition using Givens rotations is not cheap, and H must be multiplied by Q. The K matrix could be calculated using sequential measurement update, for R is always diagonal. In this method matrix inversion is not required and no additonal process is needed.

**Comment by goldbattle** [comment]
We have internally discussed changing to a sequential update in the future, but the implementation, validation, and documentation has not been started. I will leave this issue open as a reminder.

**Comment by asyounis** [comment]
Hello!  Just wondering if this is being worked on or is in the pipeline for the near future?

**Comment by goldbattle** [comment]
Not at this time.
