### ISSUE TITLE
No pose output

### ISSUE THREAD

**Issue by Jawaheru** [rpng/open_vins#443]
Hi,
I have tried to launch my own data but this warning appears, any solution?
note that when my bag file run in rviz, its speeds up for some reason.
cmd: roslaunch ov_msckf serial.launch config:=vab dataset:=Test04_newcalib

![Screenshot from 2024-05-02 11-55-44](https://github.com/rpng/open_vins/assets/100447343/ae360c40-f8a1-4692-ad23-ea67779d4ced)

**Comment by goldbattle** [comment]
You will need to change the static initialization detection to detect when you pickup the unit from the table.
The yellow warning shows that the system wasn't able to detect this increase in acceleration.
Some instructions are on this issue: https://github.com/rpng/open_vins/issues/453#issuecomment-2283164100
