### ISSUE TITLE
Maybe an error in propogate.cpp when construct discrete noise covariance matrix

### ISSUE THREAD

**Issue by WZG3661** [rpng/open_vins#446]
In `Propagate.cpp`:
https://github.com/rpng/open_vins/blob/17b73cfe4b870ade0a65f9eb217d8aab58deae19/ov_msckf/src/state/Propagator.cpp#L459-L466
why the covariance of bias is divided by `dt` not multiplied
but in the doc of IMU Propagation:
![image](https://github.com/rpng/open_vins/assets/40205539/95c3c4dd-0bdf-447e-b786-5dea6cbfe64a)
the covariance of bias is multiplied by `dt`
and in `fast_state_propagate`:
https://github.com/rpng/open_vins/blob/17b73cfe4b870ade0a65f9eb217d8aab58deae19/ov_msckf/src/state/Propagator.cpp#L220-L228

**Comment by a4msaran** [comment]
The missing dt is added in G in the function _compute_F_and_G_analytic_ and _compute_F_and_G_discrete_

https://github.com/rpng/open_vins/blob/17b73cfe4b870ade0a65f9eb217d8aab58deae19/ov_msckf/src/state/Propagator.cpp#L960C2-L961

**Comment by a4msaran** [comment]
The missing dt is added in G in the function _compute_F_and_G_analytic_ and _compute_F_and_G_discrete_

https://github.com/rpng/open_vins/blob/17b73cfe4b870ade0a65f9eb217d8aab58deae19/ov_msckf/src/state/Propagator.cpp#L960-L961

**Comment by WZG3661** [comment]
Thanks a lot!
