### ISSUE TITLE
EuRoC MAV Dataset Broken rosbag2 Download Links

### ISSUE THREAD

**Issue by chasekunz** [rpng/open_vins#449]
Hi,

Thank you for aggregating so many datasets in your docs! For the EuRoC MAV Dataset the rosbag2 links are broken. Can those be fixed?

Datasets page: [https://docs.openvins.com/gs-datasets.html](https://docs.openvins.com/gs-datasets.html)

**Comment by bsutherland333** [comment]
In the meantime you can download the [ROS1 versions](https://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets) and convert them using the [instructions for converting them to ROS2 bags](https://docs.openvins.com/dev-ros1-to-ros2.html).

**Comment by goldbattle** [comment]
Should be addressed in https://github.com/rpng/open_vins/pull/468, apologies for that.
