### ISSUE TITLE
Live state estimation not working

### ISSUE THREAD

**Issue by Jitesh2106** [rpng/open_vins#460]
Hello,
I am following the tutorial on YouTube and using an Intel D455 camera. When I run the command "roslaunch ov_msckf subscribe.launch config_path:=/home/kvl/kvl_ws/test2/rs_custom/estimator_config.yaml max_cameras:=1", I do not see any output or camera feed in RViz., the below attached image is the output I am getting on running the command.

Please provide guidance on how to resolve this issue or any steps I may have missed.
Thank you!

![question](https://github.com/user-attachments/assets/cf1c924d-cc02-408e-97c2-02b07746b8ae)

**Comment by goldbattle** [comment]
Likely some issue with the topic you are subscribing to verses the published one. What does the `rostopic list` look like?
