### ISSUE TITLE
Unity integration

### ISSUE THREAD

**Issue by igoefi** [rpng/open_vins#463]
Hello! I am a Czech student, and as a course project I chose to create an inertial navigation system in Unity. I would like to take your project as a basis.
Could you tell me what I need to study to understand all the logic, and what scripts I should pay attention to. 
Thank you very much in advance

**Comment by goldbattle** [comment]
We don't have any plans to publish a unity simulation or anything of this sort. 
You might want to checkout this project: https://github.com/uzh-rpg/flightmare
