### ISSUE TITLE
Android Port?

### ISSUE THREAD

**Issue by HardcoreBudget** [rpng/open_vins#472]
Is there an android port for open_vins that uses the phone's Monocular Camera and IMU measurements to get the 6 DoF? If not, then what scripts/libraries should I use from this repo, and what function should I feed the IMU data and camera image to?  (I only need the values of the translation and rotation without any visualizations)

**Comment by goldbattle** [comment]
No plans for an android or iOS port at this time. I think you would need to get OpenCV to run on those platforms and then try to compile portions of the code for their system.
