### ISSUE TITLE
Camera calibration values for test_webcam.cpp

### ISSUE THREAD

**Issue by Hyjale** [rpng/open_vins#50]
Hi, 

What are the specific camera calibration values needed for [test_webcam](https://github.com/rpng/open_vins/blob/e9cbfa12c8e3f4f68214d6c8303e0dce2501de57/ov_core/src/test_webcam.cpp) script on line 94? Is it in the format of "intrinsics" then distortion_coeffs?

**Comment by goldbattle** [comment]
Should be fx,fy,cx,cy,r1,r2,r3,r4.
https://docs.openvins.com/classov__core_1_1TrackBase.html#ade62fff1a5c8fad9d4bbf3ae70d676c2
These are just used to normalize the points for ransac, but in this case we set them to have focal length of 1 (i.e. ignore the camera model for ransac rejection).
