### ISSUE TITLE
OpenVINS Drifting to Infinity on Euroc Medium

### ISSUE THREAD

**Issue by apache8080** [rpng/open_vins#59]
Using the following launch file, [pgeneva_serial_eth.launch](https://github.com/rpng/open_vins/blob/master/ov_msckf/launch/pgeneva_serial_eth.launch), with OpenVINS and running the V1_02_medium dataset the poses drift to infinity. Has anybody else ran into this issue?

**Comment by goldbattle** [comment]
Are you initializing with groundtruth?
If so you probably need to change the bag start time.

It should always work from a bag_start of zero if you are not initializing
with groundtruth.
To do that you just comment out the path_gt parameter.

**Comment by apache8080** [comment]
I am not initializing with ground truth and I am starting at the beginning of the bag.

**Comment by apache8080** [comment]
I am also running without ROS.

**Comment by apache8080** [comment]
Also when I use the configuration from [this launch file](https://docs.openvins.com/gs-tutorial.html) it doesn't drift to infinity but it drifts by around 200 meters.

**Comment by apache8080** [comment]
I realized I had an issue with timing in my non ROS system.
