### ISSUE TITLE
Running Open_VINS w/o datasets

### ISSUE THREAD

**Issue by Hyjale** [rpng/open_vins#63]
Hello,

Is there a way to run OpenVINS w/o the use of datasets (ROS bags)? I have a stereo camera+IMU setup and want to feed camera/IMU data directly into Open_VINS in realtime.

**Comment by goldbattle** [comment]
The launch files with `_ros` will subscribe to a live sensor while the `_serial` will open a ros bag:
https://github.com/rpng/open_vins/tree/master/ov_msckf/launch
https://github.com/rpng/open_vins/blob/master/ov_msckf/src/ros_subscribe_msckf.cpp

You would just need to comment out the rosbag node in the bottom of the launch file, and ensure your initial calibration and topics match whatever ROS driver you are using for your sensor. Hope this helps.
