### ISSUE TITLE
launch file for KAIST dataset

### ISSUE THREAD

**Issue by bennywijaya55** [rpng/open_vins#67]
Hi, I saw that this video about demonstration of KAIST Urban 39 Dataset using OpenVins, do you mind sharing the launch file ? Thanks a lot!

**Comment by bennywijaya55** [comment]
https://www.youtube.com/watch?v=MCzTF9ye2zw

**Comment by goldbattle** [comment]
To run on that dataset, you need zero velocity update, which isn't in the repository.
We will probably make public once we release that code.

**Comment by bennywijaya55** [comment]
ah! i see! Thanks
