### ISSUE TITLE
assertion Failed in VioManagerOptions.h

### ISSUE THREAD

**Issue by ravindraji4** [rpng/open_vins#80]
Hi Patrick,

I build the project on windows (Visual Studios) using all the dependencies. The **release** and **debug** mode build were successful. 

I tried running the Simulation using the "run_simulation.cpp", but encountered the following error. 
![image](https://user-images.githubusercontent.com/26116885/86941797-a8abf500-c144-11ea-948b-00911ec0e579.png)

But unable to solve it. Could you please help how to avoid this error?

Thank you very much in advance.

**Comment by goldbattle** [comment]
I would make sure you have loaded the same number of camera extrinsics /
intrinsics as the num_camera requested.

**Comment by ravindraji4** [comment]
Thanks you!!
